'use client'
import {CreatorDraftInputSchema,CreatorDraftSchema,CreatorSubmissionRecordSchema} from '@aifans/contracts'
import {useState,type FormEvent} from 'react'
import type {Locale} from '../../i18n/config'
import {creatorJson,jsonInit} from './client'
import {ReferenceSelector} from './ReferenceSelector'
import type {CreatorDraft,CreatorLabels} from './types'
type CreatorReference=CreatorDraft['references'][number]

const authVersion='creator-operating-authorization-v1'
function lines(value:FormDataEntryValue|null){return String(value??'').split(',').map((item)=>item.trim()).filter(Boolean)}
function Field({label,name,initial='',area=false,required=true}:{label:string;name:string;initial?:string|undefined;area?:boolean;required?:boolean}){return <label className="creator-field"><span>{label}</span>{area?<textarea defaultValue={initial} name={name} required={required} rows={3}/>:<input defaultValue={initial} name={name} required={required}/>}</label>}

export function CreatorDraftForm({draft,labels,locale,onSaved,onCancel,targetIpProfileId}:{draft?:CreatorDraft;labels:CreatorLabels;locale:Locale;onSaved?(draft:CreatorDraft):void;onCancel?():void;targetIpProfileId?:string}){
  const readOnly=draft?.status==='submitted';const [references,setReferences]=useState<CreatorReference[]>(draft?.references??[]);const [accepted,setAccepted]=useState(false);const [status,setStatus]=useState<'idle'|'saving'|'saved'|'save-error'|'submitting'|'submit-error'>('idle')
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus('saving');const data=new FormData(event.currentTarget);const payload=CreatorDraftInputSchema.safeParse({...(draft?.targetIpProfileId||targetIpProfileId?{targetIpProfileId:draft?.targetIpProfileId??targetIpProfileId}:{}),username:String(data.get('username')??'').trim(),displayName:String(data.get('displayName')??'').trim(),shortDescription:String(data.get('shortDescription')??'').trim(),languageCodes:lines(data.get('languages')),contentThemes:lines(data.get('themes')),persona:{personality:String(data.get('personality')??'').trim(),background:String(data.get('background')??'').trim(),world:String(data.get('world')??'').trim(),values:String(data.get('values')??'').trim(),tone:String(data.get('tone')??'').trim(),interests:lines(data.get('interests')),boundaries:String(data.get('boundaries')??'').trim(),relationshipStyle:String(data.get('relationshipStyle')??'').trim()},visualType:String(data.get('visualType')??'hybrid'),appearance:String(data.get('appearance')??'').trim()});if(!payload.success){setStatus('save-error');return}try{const saved=CreatorDraftSchema.parse(await creatorJson(draft?`drafts/${draft.id}`:'drafts',jsonInit(draft?'PATCH':'POST',payload.data)));setStatus('saved');onSaved?.(saved)}catch{setStatus('save-error')}}
  async function submit(){if(!draft||!accepted)return;setStatus('submitting');try{CreatorSubmissionRecordSchema.parse(await creatorJson(`drafts/${draft.id}/submit`,jsonInit('POST',{authorizationVersion:authVersion,references:references.map(({id,role})=>({assetId:id,role}))})));location.reload()}catch{setStatus('submit-error')}}
  if(readOnly)return <section className="creator-editor"><p className="creator-notice">{labels.submittedReadOnly}</p><section className="creator-readonly"><header><div><strong>{draft.displayName}</strong><span>@{draft.username}</span></div><span>{labels[draft.visualType]}</span></header><p>{draft.shortDescription}</p><dl><div><dt>{labels.languages}</dt><dd>{draft.languageCodes.join(', ')}</dd></div><div><dt>{labels.themes}</dt><dd>{draft.contentThemes.join(', ')}</dd></div><div><dt>{labels.personality}</dt><dd>{draft.persona.personality}</dd></div><div><dt>{labels.background}</dt><dd>{draft.persona.background}</dd></div><div><dt>{labels.world}</dt><dd>{draft.persona.world}</dd></div><div><dt>{labels.values}</dt><dd>{draft.persona.values}</dd></div><div><dt>{labels.tone}</dt><dd>{draft.persona.tone}</dd></div><div><dt>{labels.boundaries}</dt><dd>{draft.persona.boundaries}</dd></div><div><dt>{labels.relationshipStyle}</dt><dd>{draft.persona.relationshipStyle}</dd></div><div><dt>{labels.appearance}</dt><dd>{draft.appearance}</dd></div></dl></section><ReferenceSelector draftId={draft.id} initial={references} labels={labels} readOnly/></section>
  return <section className="creator-editor"><form aria-label={labels.draftForm} className="creator-form" onSubmit={save}><header><div><p>{labels.identity}</p><h2>{draft?.displayName??labels.newIdentity}</h2></div>{onCancel?<button onClick={onCancel} type="button">{labels.cancel}</button>:null}</header><div className="creator-form-grid"><Field initial={draft?.username} label={labels.username} name="username"/><Field initial={draft?.displayName} label={labels.displayName} name="displayName"/><Field area initial={draft?.shortDescription} label={labels.shortDescription} name="shortDescription" required={false}/><Field initial={(draft?.languageCodes??[locale]).join(', ')} label={labels.languages} name="languages"/><Field initial={(draft?.contentThemes??[]).join(', ')} label={labels.themes} name="themes"/></div><fieldset className="visual-choice"><legend>{labels.visualType}</legend>{(['realistic','anime','hybrid'] as const).map((value)=><label key={value}><input defaultChecked={(draft?.visualType??'hybrid')===value} name="visualType" type="radio" value={value}/><span>{labels[value]}</span></label>)}</fieldset><h3>{labels.persona}</h3><div className="creator-form-grid"><Field area initial={draft?.persona.personality} label={labels.personality} name="personality"/><Field area initial={draft?.persona.background} label={labels.background} name="background"/><Field area initial={draft?.persona.world} label={labels.world} name="world"/><Field area initial={draft?.persona.values} label={labels.values} name="values"/><Field area initial={draft?.persona.tone} label={labels.tone} name="tone"/><Field initial={(draft?.persona.interests??[]).join(', ')} label={labels.interests} name="interests" required={false}/><Field area initial={draft?.persona.boundaries} label={labels.boundaries} name="boundaries"/><Field area initial={draft?.persona.relationshipStyle} label={labels.relationshipStyle} name="relationshipStyle"/><Field area initial={draft?.appearance} label={labels.appearance} name="appearance"/></div><button disabled={status==='saving'} type="submit">{status==='saving'?labels.saving:labels.saveDraft}</button>{status==='saved'?<p role="status">{labels.saved}</p>:null}{status==='save-error'?<p role="alert">{labels.saveError}</p>:null}</form>
    {draft?<><ReferenceSelector draftId={draft.id} initial={references} labels={labels} onChange={setReferences}/><section className="creator-authorization"><h2>{labels.authorization}</h2><p>{labels.authorizationText}</p><label><input checked={accepted} onChange={(event)=>setAccepted(event.target.checked)} type="checkbox"/>{labels.authorizationAccept}</label><button disabled={!accepted||references.length<5||status==='submitting'} onClick={submit} type="button">{status==='submitting'?labels.submitting:labels.submit}</button>{status==='submit-error'?<p role="alert">{labels.submitError}</p>:null}</section></>:null}
  </section>
}
