'use client'
import {CreatorRequestPageSchema,CreatorSubmissionPageSchema,PublicIpProfileSchema,type CreatorRequest,type CreatorSubmissionRecord,type PublicIp} from '@aifans/contracts'
import {useEffect,useState} from 'react'
import {creatorJson,jsonInit} from './client'
import type {CreatorAdminLabels} from './types'

type ReviewItem={kind:'submission';value:CreatorSubmissionRecord}|{kind:'request';value:CreatorRequest}
function Revision({value}:{value:CreatorSubmissionRecord['revision']}){return <div className="review-revision"><strong>{value.displayName}</strong><span>@{value.username}</span><dl><div><dt>Visual</dt><dd>{value.visualType}</dd></div><div><dt>Languages</dt><dd>{value.languageCodes.join(', ')}</dd></div><div><dt>Themes</dt><dd>{value.contentThemes.join(', ')}</dd></div><div><dt>Appearance</dt><dd>{value.appearance}</dd></div></dl></div>}
function CurrentIdentity({id}:{id:string}){const [value,setValue]=useState<PublicIp|null>(null);useEffect(()=>{let active=true;creatorJson(`public/profiles/${id}`).then((body)=>{if(active)setValue(PublicIpProfileSchema.parse(body).profile)}).catch(()=>{});return()=>{active=false}},[id]);return value?<div className="review-revision"><strong>{value.displayName}</strong><span>@{value.username}</span><dl><div><dt>Visual</dt><dd>{value.visualType}</dd></div><div><dt>Languages</dt><dd>{value.languages.join(', ')}</dd></div></dl></div>:<code>{id}</code>}
function ReviewCard({item,labels,onUpdated}:{item:ReviewItem;labels:CreatorAdminLabels;onUpdated(id:string):void}){const [reason,setReason]=useState('');const [status,setStatus]=useState<'idle'|'error'|'required'|'updated'>('idle');const id=item.value.id;async function decide(decision:'approve'|'reject'){if(decision==='reject'&&!reason.trim()){setStatus('required');return}try{await creatorJson(`admin/${item.kind==='submission'?'submissions':'requests'}/${id}/decision`,jsonInit('POST',{decision,...(reason.trim()?{reason:reason.trim()}: {})}));setStatus('updated');onUpdated(id)}catch{setStatus('error')}}const revision=item.kind==='submission'?item.value.revision:item.value.proposedRevision;return <article className="review-card"><header><div><strong>{item.kind==='submission'?'Submission':'Request'}</strong><code>{id}</code></div><span>{item.value.state}</span></header>{item.kind==='request'?<div className="review-compare"><section><h3>{labels.currentIdentity}</h3><CurrentIdentity id={item.value.ipProfileId}/></section><section><h3>{labels.proposedIdentity}</h3>{revision?<Revision value={revision}/>:<p>{item.value.kind}</p>}</section></div>:<section><h3>{labels.proposedIdentity}</h3><Revision value={revision!}/></section>}<label className="creator-field"><span>{labels.reason}</span><textarea aria-label={labels.reason} maxLength={2000} onChange={(event)=>setReason(event.target.value)} value={reason}/></label><div className="review-actions"><button disabled={status==='updated'} onClick={()=>void decide('approve')} type="button">{labels.approve}</button><button disabled={status==='updated'} onClick={()=>void decide('reject')} type="button">{labels.reject}</button></div>{status==='required'?<p role="alert">{labels.reasonRequired}</p>:null}{status==='error'?<p role="alert">{labels.decisionError}</p>:null}{status==='updated'?<p role="status">{labels.updated}</p>:null}</article>}

export function CreatorReviewConsole({labels}:{labels:CreatorAdminLabels}){const [submissions,setSubmissions]=useState<CreatorSubmissionRecord[]>([]);const [requests,setRequests]=useState<CreatorRequest[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');useEffect(()=>{let active=true;(async()=>{try{const submissionsPage=CreatorSubmissionPageSchema.parse(await creatorJson('admin/submissions'));const requestsPage=CreatorRequestPageSchema.parse(await creatorJson('admin/requests'));if(active){setSubmissions(submissionsPage.items);setRequests(requestsPage.items);setStatus('ready')}}catch{if(active)setStatus('error')}})();return()=>{active=false}},[]);return <main className="creator-page"><header className="creator-hero"><p>{labels.eyebrow}</p><div><h1>{labels.title}</h1></div><p>{labels.description}</p></header>{status==='loading'?<p role="status" className="creator-notice">{labels.loading}</p>:null}{status==='error'?<p role="alert" className="creator-notice">{labels.unavailable}</p>:null}<section><h2 className="creator-section-title">{labels.submissions}</h2>{status==='ready'&&!submissions.length?<p className="creator-notice">{labels.emptySubmissions}</p>:submissions.map((item)=><ReviewCard item={{kind:'submission',value:item}} key={item.id} labels={labels} onUpdated={()=>{}}/>)}</section><section><h2 className="creator-section-title">{labels.requests}</h2>{status==='ready'&&!requests.length?<p className="creator-notice">{labels.emptyRequests}</p>:requests.map((item)=><ReviewCard item={{kind:'request',value:item}} key={item.id} labels={labels} onUpdated={()=>{}}/>)}</section></main>}
