'use client'
import type {CreatorReferenceRole} from '@aifans/contracts'
import {useEffect,useState} from 'react'
import {creatorJson,jsonInit,CreatorClientError} from './client'
import type {CreatorDraft,CreatorLabels} from './types'
type CreatorReference=CreatorDraft['references'][number]

const roles:CreatorReferenceRole[]=['avatar','cover','portrait','full_body','supporting_1','supporting_2','supporting_3','supporting_4']
type UploadIntent={assetId:string;method:'PUT';url:string;headers:{'content-type':'image/jpeg'|'image/png'|'image/webp'};expiresAt:string;maxBytes:number}
function roleLabel(role:CreatorReferenceRole,labels:CreatorLabels){return ({avatar:labels.roleAvatar,cover:labels.roleCover,portrait:labels.rolePortrait,full_body:labels.roleFullBody,supporting_1:labels.roleSupporting1,supporting_2:labels.roleSupporting2,supporting_3:labels.roleSupporting3,supporting_4:labels.roleSupporting4})[role]}
async function dimensions(file:File){if(typeof createImageBitmap!=='function')throw new Error('IMAGE_DECODE_UNAVAILABLE');const image=await createImageBitmap(file);const result={width:image.width,height:image.height};image.close();return result}
function ReferencePreview({draftId,assetId,onAuthRequired}:{draftId:string;assetId:string;onAuthRequired():void}){const [url,setUrl]=useState<string>();useEffect(()=>{let active=true;creatorJson<{url:string}>(`drafts/${draftId}/references/${assetId}/read-intent`).then((intent)=>{if(active)setUrl(intent.url)}).catch((error)=>{if(active&&error instanceof CreatorClientError&&error.status===401)onAuthRequired()});return()=>{active=false}},[draftId,assetId,onAuthRequired]);return url?<img alt="" className="reference-preview" src={url}/>:<span aria-hidden="true" className="reference-placeholder"/>}

export function ReferenceSelector({draftId,initial,labels,onChange,onAuthRequired,readOnly=false}:{draftId:string;initial:CreatorReference[];labels:CreatorLabels;onChange?(references:CreatorReference[]):void;onAuthRequired():void;readOnly?:boolean}){
  const [references,setReferences]=useState(initial);const [status,setStatus]=useState<'idle'|'uploading'|'generation'|'error'|'assets-unavailable'|'generation-unavailable'>('idle')
  function update(next:CreatorReference[]){setReferences(next);onChange?.(next)}
  async function upload(file:File){setStatus('uploading');try{const intent=await creatorJson<UploadIntent>(`drafts/${draftId}/references/upload-intent`,jsonInit('POST',{contentType:file.type,sizeBytes:file.size}));const upload=await fetch(intent.url,{method:'PUT',headers:intent.headers,body:file});if(!upload.ok)throw new Error('UPLOAD_FAILED');const image=await dimensions(file);await creatorJson(`drafts/${draftId}/references`,jsonInit('POST',{assetId:intent.assetId,...image}));update([...references,{id:intent.assetId,role:roles[references.length]??'supporting_4'}]);setStatus('idle')}catch(error){if(error instanceof CreatorClientError&&error.status===401){onAuthRequired();return}setStatus(error instanceof CreatorClientError&&error.status===503?'assets-unavailable':'error')}}
  async function generate(){setStatus('generation');try{await creatorJson(`drafts/${draftId}/generation-intent`,jsonInit('POST',{}));setStatus('idle')}catch(error){if(error instanceof CreatorClientError&&error.status===401){onAuthRequired();return}setStatus(error instanceof CreatorClientError&&error.status===503?'generation-unavailable':'error')}}
  return <section className="creator-references" aria-labelledby="reference-heading"><header><div><h2 id="reference-heading">{labels.references}</h2><p>{labels.referenceCount.replace('{count}',String(references.length))}</p></div>{!readOnly?<button disabled={status==='generation'||status==='generation-unavailable'} onClick={generate} type="button">{status==='generation'?labels.generationPending:labels.generateReferences}</button>:null}</header>
    {!readOnly?<label className="creator-upload"><span>{labels.uploadReference}</span><input accept="image/jpeg,image/png,image/webp" aria-label={labels.uploadReference} disabled={references.length>=8||status==='uploading'||status==='assets-unavailable'} onChange={(event)=>{const file=event.target.files?.[0];if(file)void upload(file)}} type="file"/></label>:null}
    {status==='uploading'?<p role="status">{labels.uploading}</p>:null}{status==='error'?<p role="alert">{labels.uploadError}</p>:null}{status==='assets-unavailable'?<p className="creator-notice" role="status">{labels.assetsUnavailable}</p>:null}{status==='generation-unavailable'?<p className="creator-notice" role="status">{labels.generationUnavailable}</p>:null}
    {references.length?<ol className="reference-list">{references.map((reference,index)=><li key={reference.id}><span>{String(index+1).padStart(2,'0')}</span><ReferencePreview assetId={reference.id} draftId={draftId} onAuthRequired={onAuthRequired}/><code>{reference.id}</code>{readOnly?<strong>{roleLabel(reference.role,labels)}</strong>:<select aria-label={`${labels.referenceCount.replace('{count}',String(index+1))} ${labels.requestKind}`} onChange={(event)=>update(references.map((item,itemIndex)=>itemIndex===index?{...item,role:event.target.value as CreatorReferenceRole}:item))} value={reference.role}>{roles.map((role)=><option key={role} value={role}>{roleLabel(role,labels)}</option>)}</select>}</li>)}</ol>:null}
  </section>
}
