import {CreatorDraftSchema} from '@aifans/contracts'
import Link from 'next/link'
import {notFound} from 'next/navigation'
import {CreatorDraftForm} from '../../../../components/creator/CreatorDraftForm'
import {getMessages,isLocale} from '../../../../i18n/config'
import {fetchAifansApi} from '../../../../lib/server-api'
import {isCreatorModeEnabled} from '../../../../lib/creator-mode'
import {redirectToUserSignIn, requireAuthenticatedPage} from '../../../../lib/auth/access-policy'
export default async function CreatorDraftPage({params}:{params:Promise<{locale:string;draftId:string}>}){const {locale,draftId}=await params;if(!isCreatorModeEnabled()||!isLocale(locale))notFound();const messages=await getMessages(locale);const returnTo=`/${locale}/creator/${draftId}`;const access=await requireAuthenticatedPage({locale,returnTo});if(access.status==='unavailable')return <main className="creator-page"><header className="creator-hero"><div><h1>{messages.creator.title}</h1></div></header><p className="creator-notice" role="alert">{messages.creator.unavailable}</p></main>;let response;try{response=await fetchAifansApi(`/v1/creator/drafts/${encodeURIComponent(draftId)}`)}catch{return <main className="creator-page"><header className="creator-hero"><div><h1>{messages.creator.title}</h1></div></header><p className="creator-notice" role="alert">{messages.creator.unavailable}</p></main>}if(response.status===401)redirectToUserSignIn({locale,returnTo});if(response.status===404)notFound();if(!response.ok)return <main className="creator-page"><header className="creator-hero"><div><h1>{messages.creator.title}</h1></div></header><p className="creator-notice" role="alert">{messages.creator.unavailable}</p></main>;try{const draft=CreatorDraftSchema.parse(await response.json());return <main className="creator-page"><Link className="creator-back" href={`/${locale}/creator`}>← {messages.creator.back}</Link><CreatorDraftForm draft={draft} labels={messages.creator} locale={locale}/></main>}catch{return <main className="creator-page"><header className="creator-hero"><div><h1>{messages.creator.title}</h1></div></header><p className="creator-notice" role="alert">{messages.creator.unavailable}</p></main>}}
