import {afterEach, describe, expect, it, vi} from 'vitest'
vi.mock('../../../../../lib/auth/server.js',()=>({getApiBearerToken:vi.fn(async()=> 'signed-jwt')}))
import * as route from './route.js'

const id='22222222-2222-4222-8222-222222222222', requestId='33333333-3333-4333-8333-333333333333'
const message={id:'44444444-4444-4444-8444-444444444444',role:'human',body:'Hello',deliveryState:'sent',createdAt:'2026-09-01T01:00:00.000Z'}
const conversation={id,ipProfile:{id:'11111111-1111-4111-8111-111111111111',username:'luma',displayName:'Luma'},lastMessage:null,updatedAt:'2026-09-01T01:00:00.000Z',sendEnabled:true}
afterEach(()=>{vi.unstubAllGlobals();delete process.env.AIFANS_API_URL})
function context(value=id){return {params:Promise.resolve({conversationId:value})}}
function request(body:unknown,url=`https://web.example/api/conversations/${id}/messages`){return new Request(url,{method:'POST',headers:{origin:'https://web.example','content-type':'application/json'},body:JSON.stringify(body)})}
describe('persistent message proxy',()=>{
  it('reads strict conversation history with private no-store caching',async()=>{process.env.AIFANS_API_URL='https://internal.example';const upstream=vi.fn().mockResolvedValue(Response.json({conversation,items:[message],nextCursor:null},{headers:{'cache-control':'public, max-age=86400'}}));vi.stubGlobal('fetch',upstream);const response=await route.GET(new Request(`https://web.example/api/conversations/${id}/messages?cursor=next`),context());expect(response.status).toBe(200);expect(await response.json()).toEqual({conversation,items:[message],nextCursor:null});expect(response.headers.get('cache-control')).toBe('private, no-store');expect(upstream.mock.calls[0]?.[0]).toBe(`https://internal.example/v1/chat/conversations/${id}/messages?cursor=next`)})
  it('progressively forwards canonical CRLF SSE frames and cancels upstream on disconnect',async()=>{process.env.AIFANS_API_URL='https://internal.example';let cancelled=false;const body=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new TextEncoder().encode(`: ok\r\ndata: ${JSON.stringify({type:'human_message',message})}\r\n\r\n`))},cancel(){cancelled=true}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(body,{headers:{'content-type':'text/event-stream; charset=utf-8'}})));const response=await route.POST(request({message:' Hello ',requestId,locale:'en'}),context());const reader=response.body!.getReader();expect(new TextDecoder().decode((await reader.read()).value)).toContain('human_message');await reader.cancel();expect(cancelled).toBe(true)})
  it('forces private non-transforming SSE cache policy without reflecting upstream cache headers',async()=>{process.env.AIFANS_API_URL='https://internal.example';const raw=`data: ${JSON.stringify({type:'human_message',message})}\n\ndata: ${JSON.stringify({type:'failed',code:'CHAT_INTERRUPTED'})}\n\n`;vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(raw,{headers:{'content-type':'text/event-stream','cache-control':'public, max-age=86400','surrogate-control':'max-age=86400'}})));const response=await route.POST(request({message:'Hello',requestId}),context());expect(response.headers.get('cache-control')).toBe('private, no-cache, no-store, no-transform');expect(response.headers.has('surrogate-control')).toBe(false);await response.text()})
  it('rejects malformed UTF-8, MIME spoofs, and invalid terminal protocol safely',async()=>{process.env.AIFANS_API_URL='https://internal.example';for(const upstreamResponse of [new Response('data: {}\n\n',{headers:{'content-type':'text/event-streaming'}}),new Response(new Uint8Array([0xff]),{headers:{'content-type':'text/event-stream'}}),new Response(`data: ${JSON.stringify({type:'assistant_delta',delta:'no human first'})}\n\n`,{headers:{'content-type':'text/event-stream'}})]){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(upstreamResponse));const response=await route.POST(request({message:'Hello',requestId}),context());if(response.status===200)await expect(response.text()).rejects.toThrow();else expect(response.status).toBe(502)}})
  it.each(['trailing','eof','frame','total'])('fails unsafe %s stream after headers without exposing provider bytes',async(kind)=>{process.env.AIFANS_API_URL='https://internal.example';const human=`data: ${JSON.stringify({type:'human_message',message})}\n\n`;const complete=`data: ${JSON.stringify({type:'assistant_complete',message:{...message,role:'assistant'}})}\n\n`;const raw=kind==='trailing'?human+complete+human:kind==='eof'?human:kind==='frame'?`data: ${'x'.repeat(33_000)}\n\n`:human+'x'.repeat(1_048_577);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(raw,{headers:{'content-type':'text/event-stream'}})));const response=await route.POST(request({message:'Hello',requestId}),context());await expect(response.text()).rejects.toThrow()})
  it('decodes a multi-byte delta split across chunks',async()=>{process.env.AIFANS_API_URL='https://internal.example';const text=`data: ${JSON.stringify({type:'human_message',message})}\n\ndata: ${JSON.stringify({type:'assistant_delta',delta:'你'})}\n\ndata: ${JSON.stringify({type:'failed',code:'CHAT_INTERRUPTED'})}\n\n`;const bytes=new TextEncoder().encode(text),split=bytes.indexOf(0xe4)+1;const body=new ReadableStream<Uint8Array>({start(c){c.enqueue(bytes.slice(0,split));c.enqueue(bytes.slice(split));c.close()}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(body,{headers:{'content-type':'text/event-stream'}})));const response=await route.POST(request({message:'Hello',requestId}),context());await expect(response.text()).resolves.toContain('你')})
  it('does not continuously pre-read upstream while a downstream client is slow',async()=>{process.env.AIFANS_API_URL='https://internal.example';let pulls=0;const body=new ReadableStream<Uint8Array>({pull(controller){pulls++;controller.enqueue(new TextEncoder().encode(`data: ${JSON.stringify({type:'human_message',message})}\n\n`))}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(body,{headers:{'content-type':'text/event-stream'}})));const response=await route.POST(request({message:'Hello',requestId}),context());await Promise.resolve();expect(pulls).toBe(1);const reader=response.body!.getReader();await reader.read();expect(pulls).toBeLessThanOrEqual(2);await reader.cancel()})
  it('cancels a body rejected before SSE consumption',async()=>{process.env.AIFANS_API_URL='https://internal.example';let cancelled=false;const body=new ReadableStream({cancel(){cancelled=true}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(body,{headers:{'content-type':'application/json'}})));expect((await route.POST(request({message:'Hello',requestId}),context())).status).toBe(502);expect(cancelled).toBe(true)})
  it.each([['path',`https://web.example/api/conversations/bad/messages`,{},context('bad')],['csrf',`https://web.example/api/conversations/${id}/messages`,{'content-type':'application/json'},context()],['query',`https://web.example/api/conversations/${id}/messages?x=1`,{origin:'https://web.example','content-type':'application/json'},context()],['mime',`https://web.example/api/conversations/${id}/messages`,{origin:'https://web.example','content-type':'text/plain'},context()]])('cancels %s rejected message bodies',async(_name,url,headers,ctx)=>{let cancelled=false;const body=new ReadableStream({cancel(){cancelled=true;throw Error('ignore')}});const init={method:'POST',headers,body,duplex:'half'} as unknown as RequestInit;const response=await route.POST(new Request(url,init),ctx);expect(response.status).toBe(_name==='path'?404:_name==='csrf'?403:_name==='query'?400:422);expect(cancelled).toBe(true)})
  it.each([['invalid id',request({message:'Hello',requestId}),context('not-a-uuid')],['query',request({message:'Hello',requestId},`https://web.example/api/conversations/${id}/messages?forged=1`),context()],['duplicate',new Request(`https://web.example/api/conversations/${id}/messages`,{method:'POST',headers:{origin:'https://web.example','content-type':'application/json'},body:`{"message":"Hello","message":"Forged","requestId":"${requestId}"}`}),context()],['expanded',request({message:'Hello',requestId,providerConversationId:'secret'}),context()]])('rejects %s before upstream access',async(_name,input,ctx)=>{process.env.AIFANS_API_URL='https://internal.example';const upstream=vi.fn();vi.stubGlobal('fetch',upstream);expect((await route.POST(input,ctx)).status).toBe(_name==='invalid id'?404:_name==='query'?400:422);expect(upstream).not.toHaveBeenCalled()})
  it('rejects a non-SSE, malformed, unknown, or provider-leaking successful stream',async()=>{process.env.AIFANS_API_URL='https://internal.example';for(const upstreamResponse of [new Response('oops',{headers:{'content-type':'application/json'}}),new Response('data: nope\n\n',{headers:{'content-type':'text/event-stream'}}),new Response('data: {"type":"provider","id":"secret"}\n\n',{headers:{'content-type':'text/event-stream'}}),new Response(`data: ${JSON.stringify({type:'assistant_delta',delta:'ok',providerConversationId:'secret'})}\n\n`,{headers:{'content-type':'text/event-stream'}})]){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(upstreamResponse));const response=await route.POST(request({message:'Hello',requestId}),context());if(response.status===200)await expect(response.text()).rejects.toThrow();else expect(response.status).toBe(502)}})
})
