export interface SocialLabels {
  aiAccount: string
  authRequiredTitle: string
  authRequiredDescription: string
  bookmark: string
  bookmarksEmptyTitle: string
  bookmarksEmptyDescription: string
  likedEmptyTitle?: string
  likedEmptyDescription?: string
  commentCount: string
  comments: string
  commentsEmptyTitle?: string
  commentsEmptyDescription?: string
  commentSortChronological?: string
  deletedComment: string
  follow: string
  followingAction: string
  homeEmptyTitle: string
  homeEmptyDescription: string
  home?: string
  humanAccount: string
  interactionError: string
  loadMore: string
  aifansActor: string
  like: string
  notificationComment: string
  notificationCommentLike: string
  notificationFollow: string
  notificationPostLike: string
  notificationReply: string
  notificationsEmptyTitle: string
  notificationsEmptyDescription: string
  postNotFoundTitle: string
  postNotFoundDescription: string
  removeBookmark: string
  unlike: string
  unavailableTitle: string
  unavailableDescription: string
  unavailableRetry: string
  unavailableRetrying: string
  createdBy: string
  commentPlaceholder: string
  commentSubmit: string
  commentSending: string
  commentSuccess: string
  reply: string
  signInToComment: string
  markRead: string
  markingRead: string
  profileNotFoundTitle: string
  profileNotFoundDescription: string
  followers: string
  posts: string
  postMedia: string
  signInToInteract: string
  startChat: string
  startingChat: string
  chatStartError: string
  close?: string
  back?: string
  more?: string
  profileContentTabs?: string
  profileMedia?: string
  profileMediaEmptyTitle?: string
  profileMediaEmptyDescription?: string
  profileMediaClose?: string
  profileMediaPrevious?: string
  profileMediaNext?: string
  messages?: string
  profile?: string
  share?: string
  searchInput?: string
  searchPlaceholder?: string
  searchSubmit?: string
  searchCategory?: string
  searchAll?: string
  searchIps?: string
  searchPosts?: string
  searchResults?: string
  searchNoResults?: string
  searchNoResultsDescription?: string
  searchEnd?: string
  search?: string
  searchEmptyTitle?: string
  searchEmptyDescription?: string
  searchPopular?: string
  searchRecent?: string
  searchProfiles?: string
  searchRecommended?: string
  searchSuggestions?: string
  searchForQuery?: string
  recommendations?: string
  recommendationsEmpty?: string
}
