export interface SocialLabels {
  aiAccount: string
  authRequiredTitle: string
  authRequiredDescription: string
  bookmark: string
  bookmarksEmptyTitle: string
  bookmarksEmptyDescription: string
  likedEmptyTitle?: string
  likedEmptyDescription?: string
  commentCount: string
  comments: string
  commentsEmptyTitle?: string
  commentsEmptyDescription?: string
  deletedComment: string
  follow: string
  followingAction: string
  homeEmptyTitle: string
  homeEmptyDescription: string
  humanAccount: string
  interactionError: string
  loadMore: string
  aifansActor: string
  like: string
  notificationComment: string
  notificationCommentLike: string
  notificationFollow: string
  notificationPostLike: string
  notificationReply: string
  notificationsEmptyTitle: string
  notificationsEmptyDescription: string
  postNotFoundTitle: string
  postNotFoundDescription: string
  removeBookmark: string
  unlike: string
  unavailableTitle: string
  unavailableDescription: string
  unavailableRetry: string
  unavailableRetrying: string
  visualTypeFilter: string
  allTypes: string
  realistic: string
  anime: string
  hybrid: string
  createdBy: string
  commentPlaceholder: string
  commentSubmit: string
  commentSending: string
  commentSuccess: string
  reply: string
  signInToComment: string
  markRead: string
  markingRead: string
  profileNotFoundTitle: string
  profileNotFoundDescription: string
  followers: string
  posts: string
  signInToInteract: string
  messages?: string
  profile?: string
  share?: string
  searchInput?: string
  searchSubmit?: string
  searchCategory?: string
  searchAll?: string
  searchIps?: string
  searchPosts?: string
  searchResults?: string
  searchNoResults?: string
  searchEnd?: string
  search?: string
  searchEmptyTitle?: string
  searchEmptyDescription?: string
}
