import {afterEach, describe, expect, it, vi} from 'vitest'
vi.mock('../../../lib/auth/server.js',()=>({getApiBearerToken:vi.fn(async()=> 'signed-jwt')}))
import * as route from './route.js'

const ipProfileId='11111111-1111-4111-8111-111111111111'
const conversation={id:'22222222-2222-4222-8222-222222222222',ipProfile:{id:ipProfileId,username:'luma',displayName:'Luma'},lastMessage:null,updatedAt:'2026-09-01T01:00:00.000Z',sendEnabled:true}
afterEach(()=>{vi.unstubAllGlobals();delete process.env.AIFANS_API_URL;delete process.env.WEB_API_RATE_LIMIT_SIGNING_SECRET})
function request(body:unknown, url='https://web.example/api/conversations', headers:HeadersInit={}) {return new Request(url,{method:'POST',headers:{origin:'https://web.example','content-type':'application/json','x-request-id':'browser-request',authorization:'Bearer forged',...headers},body:JSON.stringify(body)})}

describe('persistent conversation proxy',()=>{
  it('forces private no-store caching for owner-scoped JSON without reflecting upstream cache headers',async()=>{
    process.env.AIFANS_API_URL='https://internal.example'
    vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({items:[conversation],nextCursor:null},{headers:{'cache-control':'public, max-age=86400','surrogate-control':'max-age=86400'}})))
    const response=await route.GET(new Request('https://web.example/api/conversations'))
    expect(response.status).toBe(200)
    expect(response.headers.get('cache-control')).toBe('private, no-store')
    expect(response.headers.has('surrogate-control')).toBe(false)
  })
  it('creates only a strict conversation DTO and forwards trusted server identity',async()=>{
    process.env.AIFANS_API_URL='https://internal.example'
    process.env.WEB_API_RATE_LIMIT_SIGNING_SECRET='s'.repeat(32)
    const upstream=vi.fn().mockResolvedValue(Response.json(conversation,{status:201,headers:{'x-request-id':'upstream-id'}}));vi.stubGlobal('fetch',upstream)
    const response=await route.POST(request({ipProfileId},undefined,{'x-vercel-forwarded-for':'198.51.100.1'}))
    expect(response.status).toBe(201);expect(await response.json()).toEqual(conversation);expect(response.headers.get('x-request-id')).toBe('upstream-id')
    const init=upstream.mock.calls[0]?.[1] as RequestInit;const headers=new Headers(init.headers)
    expect(upstream.mock.calls[0]?.[0]).toBe('https://internal.example/v1/chat/conversations');expect(init.body).toBe(JSON.stringify({ipProfileId}));expect(headers.get('authorization')).toBe('Bearer signed-jwt');expect(headers.get('x-request-id')).toBe('browser-request');expect(headers.has('x-aifans-rate-limit-identity')).toBe(true)
  })
  it.each([['missing origin',new Request('https://web.example/api/conversations',{method:'POST',body:'{}'})],['forwarded cross origin',request({ipProfileId},'https://private/api/conversations',{host:'web.example','x-forwarded-host':'web.example','x-forwarded-proto':'https',origin:'https://evil.example'})],['query',request({ipProfileId},'https://web.example/api/conversations?forged=1')],['duplicate key',new Request('https://web.example/api/conversations',{method:'POST',headers:{origin:'https://web.example','content-type':'application/json'},body:`{"ipProfileId":"${ipProfileId}","ipProfileId":"${ipProfileId}"}`})],['unknown key',request({ipProfileId,identity:'forged'})]])('rejects %s before upstream access',async(_name,input)=>{process.env.AIFANS_API_URL='https://internal.example';const upstream=vi.fn();vi.stubGlobal('fetch',upstream);expect((await route.POST(input)).status).toBe(_name==='query'?400:_name.includes('origin')?403:422);expect(upstream).not.toHaveBeenCalled()})
  it.each([request({ipProfileId},'https://private/api/conversations',{host:'web.example','x-forwarded-host':'evil.example','x-forwarded-proto':'https',origin:'https://evil.example'}),request({ipProfileId},'https://private/api/conversations',{host:'web.example','x-forwarded-proto':'https',origin:'https://evil.example'})])('does not allow forged forwarded hosts or protocols',async(input)=>{const upstream=vi.fn();vi.stubGlobal('fetch',upstream);expect((await route.POST(input)).status).toBe(403);expect(upstream).not.toHaveBeenCalled()})
  it.each(['application/json-evil','text/plain'])('requires an exact JSON MIME',async(contentType)=>{const response=await route.POST(request({ipProfileId},undefined,{'content-type':contentType}));expect(response.status).toBe(422)})
  it('bounds declared and streamed create bodies and keeps upstream error bodies safe',async()=>{process.env.AIFANS_API_URL='https://internal.example';const upstream=vi.fn().mockResolvedValue(new Response(JSON.stringify({code:'CHAT_TARGET_NOT_FOUND',message:'Missing',requestId:'safe'}),{status:404,headers:{'content-type':'application/json','x-request-id':'upstream'}}));vi.stubGlobal('fetch',upstream);const declared=request({ipProfileId},undefined,{'content-length':'32769'});const streamed=request({ipProfileId:'x'.repeat(40000)});expect((await route.POST(declared)).status).toBe(413);expect((await route.POST(streamed)).status).toBe(413);const response=await route.POST(request({ipProfileId}));expect(response.status).toBe(404);expect(await response.json()).toEqual({code:'CHAT_TARGET_NOT_FOUND',message:'Missing',requestId:'safe'});expect(response.headers.get('x-request-id')).toBe('upstream')})
  it.each([['declared',new Response('x',{status:500,headers:{'content-length':'32769'}})],['streamed',new Response('x'.repeat(32769),{status:500})],['html',new Response('<secret>',{status:500,headers:{'content-type':'text/html'}})]])('maps unsafe %s upstream errors to canonical JSON',async(_kind,error)=>{process.env.AIFANS_API_URL='https://internal.example';vi.stubGlobal('fetch',vi.fn().mockResolvedValue(error));const response=await route.POST(request({ipProfileId}));expect(response.status).toBe(502);expect(response.headers.get('content-type')).toContain('application/json');expect(await response.json()).toEqual({code:'CHAT_INVALID_RESPONSE'})})
  it('cancels declared request and upstream error bodies',async()=>{process.env.AIFANS_API_URL='https://internal.example';let requestCancelled=false,errorCancelled=false;const requestBody=new ReadableStream({cancel(){requestCancelled=true}});const init={method:'POST',headers:{origin:'https://web.example','content-type':'application/json','content-length':'32769'},body:requestBody as ReadableStream,duplex:'half'} as unknown as RequestInit;const oversized=new Request('https://web.example/api/conversations',init);expect((await route.POST(oversized)).status).toBe(413);expect(requestCancelled).toBe(true);const errorBody=new ReadableStream({cancel(){errorCancelled=true}});vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(errorBody,{status:500,headers:{'content-type':'application/json','content-length':'32769'}})));expect((await route.POST(request({ipProfileId}))).status).toBe(502);expect(errorCancelled).toBe(true)})
  it('rejects valid error JSON labelled as HTML and canonicalizes success DTO MIME',async()=>{process.env.AIFANS_API_URL='https://internal.example';const error={code:'SAFE',message:'safe',requestId:'req'};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(error),{status:500,headers:{'content-type':'text/html'}})));expect((await route.POST(request({ipProfileId}))).status).toBe(502);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify(conversation),{status:201,headers:{'content-type':'text/html'}})));const response=await route.POST(request({ipProfileId}));expect(response.status).toBe(201);expect(response.headers.get('content-type')).toContain('application/json')})
  it.each([['csrf','https://web.example/api/conversations',{'content-type':'application/json'}],['query','https://web.example/api/conversations?x=1',{origin:'https://web.example','content-type':'application/json'}],['mime','https://web.example/api/conversations',{origin:'https://web.example','content-type':'text/plain'}]])('cancels %s rejected request bodies',async(_name,url,headers)=>{let cancelled=false;const body=new ReadableStream({cancel(){cancelled=true;throw Error('ignore')}});const init={method:'POST',headers,body,duplex:'half'} as unknown as RequestInit;const response=await route.POST(new Request(url,init));expect(response.status).toBe(_name==='csrf'?403:_name==='query'?400:422);expect(cancelled).toBe(true)})
})
