import {randomUUID} from 'node:crypto'
import {describe,expect,it,vi} from 'vitest'
import {createApp} from '../application.js'
import type {PlatformChannelPort} from '../ports/channels.js'

const id=randomUUID();const now='2026-09-04T00:00:00.000Z';const record={id,slug:'ai-news',name:'AI News',description:'',imageUrl:null,ipCount:0,status:'draft' as const,sortOrder:0,aliases:[],createdAt:now,updatedAt:now}
function deps(operator=true){const platformChannels:PlatformChannelPort={listChannels:vi.fn(async()=>({items:[],nextCursor:null})),getChannel:vi.fn(async()=>record),createChannel:vi.fn(async()=>record),updateChannel:vi.fn(async()=>record),setStatus:vi.fn(async()=>undefined),replaceAliases:vi.fn(async()=>undefined),setMembership:vi.fn(async()=>undefined),removeMembership:vi.fn(async()=>undefined)};return {auth:{verify:vi.fn(async()=>({status:'authenticated' as const,identity:{subject:'operator'}}))},profiles:{ensureHumanProfile:vi.fn(async()=>undefined),getCurrentAccount:vi.fn(async()=>({id,kind:'human' as const,username:'operator',displayName:'Operator',preferredLocale:'en' as const,creatorModeEnabled:false}))},authority:{isCurrentActorOperator:vi.fn(async()=>operator)},platformChannels}}
describe('operator channel routes',()=>{
 it('lists all channel statuses for operators with strict filters',async()=>{const dependencies=deps();dependencies.platformChannels.listChannels=vi.fn(async()=>({items:[record],nextCursor:null}));const response=await createApp(dependencies).request('/v1/admin/channels?q=AI&status=draft&limit=25');expect(response.status).toBe(200);expect(dependencies.platformChannels.listChannels).toHaveBeenCalledWith({actor:{subject:'operator'},query:{q:'AI',status:'draft',limit:25}});expect((await response.json()).items[0]).toMatchObject({id,status:'draft',aliases:[],ipCount:0});expect((await createApp(dependencies).request('/v1/admin/channels?limit=1&limit=2')).status).toBe(400)})
 it('requires an active operator',async()=>{const dependencies=deps(false);expect((await createApp(dependencies).request('/v1/admin/channels',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'ai-news',name:'AI News'})})).status).toBe(403);expect(dependencies.platformChannels.createChannel).not.toHaveBeenCalled()})
 it('gets one channel by id for an active operator',async()=>{const dependencies=deps();const response=await createApp(dependencies).request(`/v1/admin/channels/${id}`);expect(response.status).toBe(200);expect(dependencies.platformChannels.getChannel).toHaveBeenCalledWith({actor:{subject:'operator'},channelId:id});expect(await response.json()).toEqual(record)})
 it('strictly validates operator channel reads',async()=>{const dependencies=deps();const app=createApp(dependencies);expect((await app.request('/v1/admin/channels/not-a-uuid')).status).toBe(400);expect((await app.request(`/v1/admin/channels/${id}?unexpected=1`)).status).toBe(400);expect(dependencies.platformChannels.getChannel).not.toHaveBeenCalled()})
 it('requires authentication and operator authority for channel reads',async()=>{const unauthenticated=deps();unauthenticated.auth.verify=vi.fn(async()=>({status:'missing' as const}));expect((await createApp(unauthenticated).request(`/v1/admin/channels/${id}`)).status).toBe(401);expect(unauthenticated.platformChannels.getChannel).not.toHaveBeenCalled();const forbidden=deps(false);expect((await createApp(forbidden).request(`/v1/admin/channels/${id}`)).status).toBe(403);expect(forbidden.platformChannels.getChannel).not.toHaveBeenCalled()})
 it('returns CHANNEL_NOT_FOUND when an operator channel id is missing',async()=>{const dependencies=deps();dependencies.platformChannels.getChannel=vi.fn(async()=>null);const response=await createApp(dependencies).request(`/v1/admin/channels/${id}`);expect(response.status).toBe(404);expect(await response.json()).toMatchObject({code:'CHANNEL_NOT_FOUND'})})
 it('creates, edits, publishes, archives, aliases and memberships with request IDs',async()=>{const dependencies=deps();const app=createApp(dependencies);expect((await app.request('/v1/admin/channels',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug:'ai-news',name:'AI News'})})).status).toBe(201);expect((await app.request(`/v1/admin/channels/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({sortOrder:2})})).status).toBe(200);for(const action of ['publish','archive'])expect((await app.request(`/v1/admin/channels/${id}/${action}`,{method:'POST'})).status).toBe(204);expect((await app.request(`/v1/admin/channels/${id}/aliases`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({aliases:['人工智能']})})).status).toBe(204);expect((await app.request(`/v1/admin/channels/${id}/profiles`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({ipProfileId:id,isPrimary:true,curationWeight:4})})).status).toBe(204);expect(dependencies.platformChannels.createChannel).toHaveBeenCalledWith(expect.objectContaining({actor:{subject:'operator'},requestId:expect.any(String)}))})
 it('rejects duplicate JSON fields and invalid ids',async()=>{const app=createApp(deps());expect((await app.request('/v1/admin/channels',{method:'POST',headers:{'content-type':'application/json'},body:'{"slug":"ai-news","slug":"other","name":"AI"}'})).status).toBe(422);expect((await app.request('/v1/admin/channels/nope/publish',{method:'POST'})).status).toBe(400)})
 it.each([
  ['status','POST',`/v1/admin/channels/${id}/publish`,undefined,'CHANNEL_NOT_FOUND',404],
  ['aliases','PUT',`/v1/admin/channels/${id}/aliases`,{aliases:['AI']},'CHANNEL_NOT_FOUND',404],
  ['member foreign key','PUT',`/v1/admin/channels/${id}/profiles`,{ipProfileId:id,isPrimary:false,curationWeight:0},'CHANNEL_NOT_FOUND',404],
  ['member conflict','PUT',`/v1/admin/channels/${id}/profiles`,{ipProfileId:id,isPrimary:true,curationWeight:0},'CHANNEL_CONFLICT',409],
  ['member check','PUT',`/v1/admin/channels/${id}/profiles`,{ipProfileId:id,isPrimary:false,curationWeight:0},'INVALID_REQUEST',422],
  ['remove','DELETE',`/v1/admin/channels/${id}/profiles/${id}`,undefined,'CHANNEL_NOT_FOUND',404],
 ] as const)('maps %s mutation failures instead of returning 204',async(_name,method,path,body,code,status)=>{const dependencies=deps();const errorCode=code==='CHANNEL_CONFLICT'?'23505':code==='INVALID_REQUEST'?'23514':_name==='member foreign key'?'23503':'P0002';const methodName=_name==='status'?'setStatus':_name==='aliases'?'replaceAliases':_name==='remove'?'removeMembership':'setMembership';vi.mocked(dependencies.platformChannels[methodName]).mockRejectedValue(Object.assign(new Error('write failed'),{code:errorCode}));const response=await createApp(dependencies).request(path,{method,headers:{'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});expect(response.status).toBe(status);expect(await response.json()).toMatchObject({code})})
})
