import {AdminChannelPageSchema,AdminChannelQuerySchema,ChannelRecordSchema,CreateChannelSchema,ReplaceChannelAliasesSchema,SetChannelMembershipSchema,UpdateChannelSchema,decodeChannelCursor} from '@aifans/contracts'
import type {Actor} from '@aifans/db'
import type {Context,Hono} from 'hono'
import {z} from 'zod'
import {apiError} from '../errors.js'
import type {ApiVariables} from '../middleware/request-id.js'
import type {AuthVerifier} from '../ports/auth.js'
import type {AuthorityPort} from '../ports/authority.js'
import type {PlatformChannelPort} from '../ports/channels.js'
import type {ProfilePort} from '../ports/profiles.js'
import {strictJsonBody,strictQuery} from './strict-input.js'
type Ctx=Context<{Variables:ApiVariables}>
export type AdminChannelDependencies={auth?:AuthVerifier;profiles?:ProfilePort;authority?:AuthorityPort;platformChannels?:PlatformChannelPort}
async function operator(c:Ctx,d:AdminChannelDependencies):Promise<Actor|Response>{if(!d.auth)return apiError(c,503,'AUTH_NOT_CONFIGURED','Authentication is not configured');const auth=await d.auth.verify(c.req.raw);if(auth.status==='missing')return apiError(c,401,'AUTH_REQUIRED','Authentication is required');if(auth.status!=='authenticated'||!auth.identity.subject.trim())return apiError(c,401,'AUTH_INVALID','Authentication is invalid');if(!d.profiles)return apiError(c,503,'PROFILE_NOT_CONFIGURED','Profiles are not configured');const actor={subject:auth.identity.subject};await d.profiles.ensureHumanProfile({authSubject:actor.subject,...(auth.identity.email===undefined?{}:{email:auth.identity.email}),...(auth.identity.displayName===undefined?{}:{displayName:auth.identity.displayName})});if((await d.profiles.getCurrentAccount(actor))?.kind!=='human')return apiError(c,403,'HUMAN_REQUIRED','A human account is required');if(!d.authority)return apiError(c,503,'AUTHORITY_NOT_CONFIGURED','Authority is not configured');if(!await d.authority.isCurrentActorOperator(actor))return apiError(c,403,'OPERATOR_REQUIRED','An active operator is required');return actor}
const empty=z.strictObject({});const uuid=z.uuid()
function clean(c:Ctx){return strictQuery(c,empty)!==null}
function id(c:Ctx,name='channelId'){const value=uuid.safeParse(c.req.param(name));return value.success?value.data:null}
async function authorized(c:Ctx,d:AdminChannelDependencies){const actor=await operator(c,d);if(actor instanceof Response)return actor;if(!d.platformChannels)return apiError(c,503,'CHANNELS_NOT_CONFIGURED','Channels are not configured');return {actor,port:d.platformChannels}}
function channelError(c:Ctx,error:unknown):Response{const candidate=error as {code?:string;message?:string};if(candidate.code==='42501')return apiError(c,403,'OPERATOR_REQUIRED','An active operator is required');if(candidate.code==='P0002'||candidate.code==='23503'||/not found/i.test(candidate.message??''))return apiError(c,404,'CHANNEL_NOT_FOUND','Channel was not found');if(candidate.code==='23505')return apiError(c,409,'CHANNEL_CONFLICT','Channel conflicts with existing data');if(candidate.code==='23514')return apiError(c,422,'INVALID_REQUEST','Request is invalid');if(candidate.message==='INVALID_CURSOR')return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');throw error}
export function registerAdminChannelRoutes(app:Hono<{Variables:ApiVariables}>,d:AdminChannelDependencies){
 app.get('/v1/admin/channels',async c=>{const query=strictQuery(c,AdminChannelQuerySchema);if(!query)return apiError(c,400,'INVALID_REQUEST','Request is invalid');try{if(query.cursor)decodeChannelCursor(query.cursor,'admin_channels');const access=await authorized(c,d);if(access instanceof Response)return access;return c.json(AdminChannelPageSchema.parse(await access.port.listChannels({actor:access.actor,query})))}catch(error){return channelError(c,error)}})
 app.get('/v1/admin/channels/:channelId',async c=>{const channelId=id(c);if(!clean(c)||!channelId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;const channel=await access.port.getChannel({actor:access.actor,channelId});return channel?c.json(ChannelRecordSchema.parse(channel)):apiError(c,404,'CHANNEL_NOT_FOUND','Channel was not found')}catch(error){return channelError(c,error)}})
 app.post('/v1/admin/channels',async c=>{if(!clean(c))return apiError(c,400,'INVALID_REQUEST','Request is invalid');const body=await strictJsonBody(c,CreateChannelSchema);if(!body)return apiError(c,422,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;return c.json(ChannelRecordSchema.parse(await access.port.createChannel({actor:access.actor,requestId:c.get('requestId'),channel:body})),201)}catch(error){return channelError(c,error)}})
 app.patch('/v1/admin/channels/:channelId',async c=>{const channelId=id(c);if(!clean(c)||!channelId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');const body=await strictJsonBody(c,UpdateChannelSchema);if(!body)return apiError(c,422,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;return c.json(ChannelRecordSchema.parse(await access.port.updateChannel({actor:access.actor,requestId:c.get('requestId'),channelId,channel:body})))}catch(error){return channelError(c,error)}})
 for(const [action,status] of [['publish','published'],['archive','archived']] as const)app.post(`/v1/admin/channels/:channelId/${action}`,async c=>{const channelId=id(c);if(!clean(c)||!channelId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;await access.port.setStatus({actor:access.actor,requestId:c.get('requestId'),channelId,status});return c.body(null,204)}catch(error){return channelError(c,error)}})
 app.put('/v1/admin/channels/:channelId/aliases',async c=>{const channelId=id(c);if(!clean(c)||!channelId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');const body=await strictJsonBody(c,ReplaceChannelAliasesSchema);if(!body)return apiError(c,422,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;await access.port.replaceAliases({actor:access.actor,requestId:c.get('requestId'),channelId,aliases:body});return c.body(null,204)}catch(error){return channelError(c,error)}})
 app.put('/v1/admin/channels/:channelId/profiles',async c=>{const channelId=id(c);if(!clean(c)||!channelId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');const body=await strictJsonBody(c,SetChannelMembershipSchema);if(!body)return apiError(c,422,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;await access.port.setMembership({actor:access.actor,requestId:c.get('requestId'),channelId,membership:body});return c.body(null,204)}catch(error){return channelError(c,error)}})
 app.delete('/v1/admin/channels/:channelId/profiles/:profileId',async c=>{const channelId=id(c),profileId=id(c,'profileId');if(!clean(c)||!channelId||!profileId)return apiError(c,400,'INVALID_REQUEST','Request is invalid');try{const access=await authorized(c,d);if(access instanceof Response)return access;await access.port.removeMembership({actor:access.actor,requestId:c.get('requestId'),channelId,ipProfileId:profileId});return c.body(null,204)}catch(error){return channelError(c,error)}})
}
