import {ChannelDetailSchema,ChannelIpPageSchema,ChannelPageQuerySchema,ChannelPageSchema,ChannelPostPageSchema,ChannelQuerySchema,ChannelSlugSchema,decodeChannelCursor} from '@aifans/contracts'
import type {Hono} from 'hono'
import {apiError} from '../errors.js'
import type {ApiVariables} from '../middleware/request-id.js'
import type {ChannelPort} from '../ports/channels.js'
import {strictQuery} from './strict-input.js'

export type ChannelDependencies={channels?:ChannelPort}
function invalid(c:Parameters<typeof apiError>[0]){return apiError(c,400,'INVALID_REQUEST','Request is invalid')}
function validateCursor(cursor:string|undefined,kind:'channel_directory'|'channel_ips'|'channel_posts'){return cursor?decodeChannelCursor(cursor,kind):null}
export function registerChannelRoutes(app:Hono<{Variables:ApiVariables}>,dependencies:ChannelDependencies){
 app.get('/v1/channels',async c=>{const query=strictQuery(c,ChannelQuerySchema);if(!query)return invalid(c);if(!dependencies.channels)return apiError(c,503,'CHANNELS_NOT_CONFIGURED','Channels are not configured');try{validateCursor(query.cursor,'channel_directory');return c.json(ChannelPageSchema.parse(await dependencies.channels.listChannels(query)))}catch(error){if(error instanceof Error&&error.message==='INVALID_CURSOR')return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');throw error}})
 app.get('/v1/channels/:slug',async c=>{const query=strictQuery(c,ChannelPageQuerySchema.pick({}));const slug=ChannelSlugSchema.safeParse(c.req.param('slug'));if(!query||!slug.success)return invalid(c);if(!dependencies.channels)return apiError(c,503,'CHANNELS_NOT_CONFIGURED','Channels are not configured');const value=await dependencies.channels.getChannel(slug.data);return value?c.json(ChannelDetailSchema.parse(value)):apiError(c,404,'CHANNEL_NOT_FOUND','Channel was not found')})
 app.get('/v1/channels/:slug/profiles',async c=>{const query=strictQuery(c,ChannelPageQuerySchema);const slug=ChannelSlugSchema.safeParse(c.req.param('slug'));if(!query||!slug.success)return invalid(c);if(!dependencies.channels)return apiError(c,503,'CHANNELS_NOT_CONFIGURED','Channels are not configured');try{const cursor=validateCursor(query.cursor,'channel_ips');const channel=await dependencies.channels.getChannel(slug.data,0);if(!channel)return apiError(c,404,'CHANNEL_NOT_FOUND','Channel was not found');if(cursor?.kind==='channel_ips'&&cursor.channelId!==channel.id)return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');return c.json(ChannelIpPageSchema.parse(await dependencies.channels.listProfiles(slug.data,query)))}catch(error){if(error instanceof Error&&error.message==='INVALID_CURSOR')return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');throw error}})
 app.get('/v1/channels/:slug/posts',async c=>{const query=strictQuery(c,ChannelPageQuerySchema);const slug=ChannelSlugSchema.safeParse(c.req.param('slug'));if(!query||!slug.success)return invalid(c);if(!dependencies.channels)return apiError(c,503,'CHANNELS_NOT_CONFIGURED','Channels are not configured');try{const cursor=validateCursor(query.cursor,'channel_posts');const channel=await dependencies.channels.getChannel(slug.data,0);if(!channel)return apiError(c,404,'CHANNEL_NOT_FOUND','Channel was not found');if(cursor?.kind==='channel_posts'&&cursor.channelId!==channel.id)return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');return c.json(ChannelPostPageSchema.parse(await dependencies.channels.listPosts(slug.data,query)))}catch(error){if(error instanceof Error&&error.message==='INVALID_CURSOR')return apiError(c,400,'INVALID_CURSOR','Cursor is invalid');throw error}})
}
