import {randomUUID} from 'node:crypto'
import {Pool, type PoolClient} from 'pg'
import {afterAll, describe, expect, it} from 'vitest'
import {decodeCursor, decodeFollowedIpCursor, decodeLikedCursor, encodeCursor, encodeNotificationCursor} from '@aifans/contracts'
import {createSocialRepository} from '../src/social.js'
import {createActorSession} from '../src/session.js'

const connectionString=process.env.DATABASE_URL ?? ''
const integration=connectionString ? describe : describe.skip
const pool=new Pool({connectionString})
async function tx<T>(fn:(c:PoolClient)=>Promise<T>) { const c=await pool.connect(); try { await c.query('BEGIN'); return await fn(c) } finally { await c.query('ROLLBACK').catch(()=>undefined); c.release() } }
async function human(c:PoolClient) { const id=randomUUID(), subject=`fixture-${randomUUID()}`; await c.query(`INSERT INTO public.profiles(id,auth_subject,account_kind,username,display_name) VALUES($1,$2,'human',$3,'Human')`,[id,subject,`h_${id.replaceAll('-','').slice(0,20)}`]); return {id,subject} }
async function ip(c:PoolClient, state:'published'|'draft'='published') { const id=randomUUID(), revision=randomUUID(); await c.query(`INSERT INTO public.profiles(id,account_kind,username,display_name) VALUES($1,'ip',$2,'IP')`,[id,`i_${id.replaceAll('-','').slice(0,20)}`]); await c.query(`INSERT INTO public.ip_profiles(profile_id,source,public_state,operation_enabled,current_identity_revision_id) VALUES($1,'platform',$2,true,$3)`,[id,state,revision]); await c.query(`INSERT INTO public.ip_identity_revisions(id,ip_profile_id,version,display_name,languages) VALUES($1,$2,1,'IP',ARRAY['en'])`,[revision,id]); return id }
async function post(c:PoolClient, author:string, state:'published'|'draft'|'withdrawn'='published', publishedAt?:string, languageCode?:'en'|'zh-CN') { const id=randomUUID(); const timestamp=publishedAt??new Date().toISOString(); if(state==='draft') await c.query(`INSERT INTO public.posts(id,author_profile_id,source,state,body,language_code) VALUES($1,$2,'worker',$3,'fixture',$4)`,[id,author,state,languageCode??null]); else if(state==='published') await c.query(`INSERT INTO public.posts(id,author_profile_id,source,state,body,published_at,language_code) VALUES($1,$2,'worker',$3,'fixture',$4::timestamptz,$5)`,[id,author,state,timestamp,languageCode??null]); else await c.query(`INSERT INTO public.posts(id,author_profile_id,source,state,body,published_at,withdrawn_at,language_code) VALUES($1,$2,'worker',$3,'fixture',$4::timestamptz,$4::timestamptz,$5)`,[id,author,state,timestamp,languageCode??null]); return id }
function notificationCursor(createdAt:string,id:string) { return encodeNotificationCursor({v:1,kind:'notifications',createdAt,id}) }
function context() { return {requestId: randomUUID()} }
function repo(c:PoolClient) { const session=createActorSession({connect:async()=>({query:c.query.bind(c),release(){}})}, {transactionMode:'nested'}); return createSocialRepository({withActor:session.withActor,withPublic:async(fn)=>{await c.query('SAVEPOINT anon'); try {await c.query('SET LOCAL ROLE aifans_anon'); await c.query("SELECT set_config('request.jwt.claims','{}',true)"); const value=await fn({query:c.query.bind(c),release(){}}); await c.query('ROLLBACK TO SAVEPOINT anon'); return value} finally {await c.query('RELEASE SAVEPOINT anon').catch(()=>undefined)}}}) }

async function committedCommentFixture() {
 const client=await pool.connect()
 try {
  await client.query('BEGIN')
  const author=await ip(client),actor=await human(client),postId=await post(client,author)
  await client.query('COMMIT')
  return {actor,author,postId}
 } catch(error) { await client.query('ROLLBACK').catch(()=>undefined); throw error } finally { client.release() }
}

async function expectVisibilityChangeToWin(change:(client:PoolClient,fixture:Awaited<ReturnType<typeof committedCommentFixture>>)=>Promise<void>) {
 const fixture=await committedCommentFixture(),stateClient=await pool.connect(),commentClient=await pool.connect()
 try {
  await stateClient.query('BEGIN')
  await change(stateClient,fixture)
  await commentClient.query('BEGIN')
  const commentPid=(await commentClient.query<{pid:number}>('SELECT pg_backend_pid() AS pid')).rows[0]!.pid
  const attempt=repo(commentClient).createHumanComment(fixture.actor,fixture.postId,{body:'racing comment'},context()).then(()=>({ok:true as const})).catch((error:unknown)=>({ok:false as const,error}))
  let blocked=false
  for(let poll=0;poll<50;poll+=1) {
   const activity=await stateClient.query<{wait_event_type:string|null}>('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1',[commentPid])
   if(activity.rows[0]?.wait_event_type==='Lock') { blocked=true;break }
   const settled=await Promise.race([attempt.then(()=>true),new Promise<false>((resolve)=>setTimeout(()=>resolve(false),10))])
   if(settled) break
  }
  await stateClient.query('COMMIT')
  const outcome=await attempt
  expect(blocked).toBe(true)
  expect(outcome.ok).toBe(false)
  if(!outcome.ok) expect(outcome.error).toMatchObject({code:'P0002'})
  await expect(stateClient.query("SELECT 1 FROM public.comments WHERE post_id=$1 AND body='racing comment'",[fixture.postId])).resolves.toMatchObject({rowCount:0})
 } finally {
  await Promise.all([stateClient.query('ROLLBACK').catch(()=>undefined),commentClient.query('ROLLBACK').catch(()=>undefined)])
  stateClient.release();commentClient.release()
 }
}

integration('social repository local postgres',()=>{
 afterAll(async()=>pool.end())
 it('returns only published public posts and keeps viewer flags actor-scoped',async()=>tx(async c=>{
  const author=await ip(c); const hidden=await ip(c,'draft'); const visible=await post(c,author); await post(c,hidden); await post(c,author,'withdrawn');
  const first=await human(c), second=await human(c); const social=repo(c);
  const ownerProjection=await c.query('SELECT post_id FROM public.social_public_posts()'); expect(ownerProjection.rows.map((row)=>row.post_id)).toContain(visible);
  await c.query('SAVEPOINT diagnostic_anon'); await c.query('SET LOCAL ROLE aifans_anon'); const anonProjection=await c.query('SELECT post_id FROM public.social_public_posts()'); const flags=await c.query('SELECT * FROM public.social_viewer_flags($1,$2)',[visible,author]); const metrics=await c.query('SELECT * FROM public.social_post_metrics($1,$2,$3)',[visible,author,'en']); const identity=await c.query("SELECT current_user, current_setting('request.jwt.claims',true) AS claims"); await c.query('ROLLBACK TO SAVEPOINT diagnostic_anon'); await c.query('RELEASE SAVEPOINT diagnostic_anon'); expect(identity.rows[0]?.current_user).toBe('aifans_anon'); expect(anonProjection.rows.map((row)=>row.post_id)).toContain(visible); expect(flags.rows).toHaveLength(1); expect(metrics.rows).toHaveLength(1);
  await social.likePost(first,visible,context()); await social.bookmarkPost(first,visible); await social.follow(first,author,context());
  const anon=await social.listFeed({viewer:null,kind:'for_you',limit:25,after:null}); expect(anon.items.map(x=>x.id)).toEqual([visible]); expect(anon.items[0]?.likeCount).toBe(1); expect(anon.items[0]?.viewerHasLiked).toBe(false); expect(anon.items[0]?.author.followerCount).toBe(1);
  const mine=await social.listFeed({viewer:first,kind:'for_you',limit:25,after:null}); expect(mine.items[0]).toMatchObject({viewerHasLiked:true,viewerHasBookmarked:true,viewerFollowsAuthor:true});
  const other=await social.listFeed({viewer:second,kind:'for_you',limit:25,after:null}); expect(other.items[0]).toMatchObject({viewerHasLiked:false,viewerHasBookmarked:false,viewerFollowsAuthor:false});
 }))
 it('returns only published current IP profiles with paginated posts and viewer follow state',async()=>tx(async c=>{ const visible=await ip(c),hidden=await ip(c,'draft'),viewer=await human(c),social=repo(c); const older=await post(c,visible,'published','2026-09-01T00:00:00.000Z'); const newer=await post(c,visible,'published','2026-09-01T01:00:00.000Z'); await social.follow(viewer,visible,context()); const anonymous=await social.getPublicProfile({viewer:null,profileId:visible,limit:1,after:null}); expect(anonymous).toMatchObject({profile:{id:visible,kind:'ip'},followerCount:1,posts:{items:[{id:newer}]}}); expect(anonymous).not.toHaveProperty('viewerFollows'); expect(anonymous?.posts.nextCursor).toBeTruthy(); const after=decodeCursor(anonymous!.posts.nextCursor!,'following'); await expect(social.getPublicProfile({viewer:null,profileId:visible,limit:1,after})).resolves.toMatchObject({posts:{items:[{id:older}],nextCursor:null}}); await expect(social.getPublicProfile({viewer,profileId:visible,limit:10,after:null})).resolves.toMatchObject({viewerFollows:true}); await expect(social.getPublicProfile({viewer:null,profileId:hidden,limit:10,after:null})).resolves.toBeNull(); await expect(social.getPublicProfile({viewer:null,profileId:randomUUID(),limit:10,after:null})).resolves.toBeNull() }))
 it('uses the documented absolute score and changes order for the viewer relationship',async()=>tx(async c=>{ const publishedAt='2026-09-01T00:00:00.000Z'; const firstAuthor=await ip(c),secondAuthor=await ip(c); await c.query('UPDATE public.ip_profiles SET feed_weight=7 WHERE profile_id=$1',[firstAuthor]); const firstPost=await post(c,firstAuthor,'published',publishedAt,'en'),secondPost=await post(c,secondAuthor,'published',publishedAt); const viewer=await human(c),liker=await human(c),social=repo(c); await social.likePost(liker,firstPost,context()); const commentId=randomUUID(); await c.query(`INSERT INTO public.comments(id,post_id,author_profile_id,source,body) VALUES($1,$2,$3,'human','score')`,[commentId,firstPost,viewer.id]); const score=await createActorSession({connect:async()=>({query:c.query.bind(c),release(){}})}, {transactionMode:'nested'}).withActor(viewer,async client=>(await client.query<{score:string;like_count:number;comment_count:number}>('SELECT * FROM public.social_post_metrics($1,$2,$3)',[firstPost,firstAuthor,'en'])).rows[0]!); expect(Number(score.score)).toBe(Date.parse(publishedAt)/3_600_000+7+10+2+3); expect(score).toMatchObject({like_count:1,comment_count:1}); const anonymous=await social.listFeed({viewer:null,kind:'for_you',limit:10,after:null}); const lower=anonymous.items.findIndex(item=>item.id===firstPost)>anonymous.items.findIndex(item=>item.id===secondPost)?{author:firstAuthor,post:firstPost}:{author:secondAuthor,post:secondPost}; await social.follow(viewer,lower.author,context()); const personalized=await social.listFeed({viewer,kind:'for_you',limit:10,after:null}); expect(personalized.items[0]?.id).toBe(lower.post) }))
 it('paginates every feed post once while preserving database microseconds',async()=>tx(async c=>{ const author=await ip(c); const ids=[await post(c,author,'published','2026-09-01T00:00:00.000100Z'),await post(c,author,'published','2026-09-01T00:00:00.000500Z'),await post(c,author,'published','2026-09-01T00:00:00.000900Z')]; const viewer=await human(c),social=repo(c); await social.follow(viewer,author,context()); for (const kind of ['for_you','following'] as const) { const found:string[]=[]; let after=null; do { const page=await social.listFeed({viewer:kind==='following'?viewer:null,kind,limit:1,after}); found.push(...page.items.map(item=>item.id)); after=page.nextCursor?decodeCursor(page.nextCursor,kind):null } while(after); expect(found).toEqual(ids.slice().reverse()); expect(new Set(found).size).toBe(ids.length) } }))
 it('rejects commands against posts and IPs outside the public current projection',async()=>tx(async c=>{ const actor=await human(c); const author=await ip(c); const draft=await post(c,author,'draft'); const withdrawn=await post(c,author,'withdrawn'); const hidden=await ip(c,'draft'); const hiddenPost=await post(c,hidden); const missing=randomUUID(); const social=repo(c); await expect(social.createHumanComment(actor,draft,{body:'no'},context())).rejects.toThrow(); await expect(social.createHumanComment(actor,withdrawn,{body:'no'},context())).rejects.toThrow(); await expect(social.follow(actor,hidden,context())).rejects.toThrow(); await expect(social.likePost(actor,hiddenPost,context())).rejects.toThrow(); for(const command of [()=>social.bookmarkPost(actor,hiddenPost),()=>social.bookmarkPost(actor,missing),()=>social.unfollow(actor,hidden),()=>social.unfollow(actor,missing),()=>social.unlikePost(actor,hiddenPost),()=>social.unlikePost(actor,missing),()=>social.unbookmarkPost(actor,hiddenPost),()=>social.unbookmarkPost(actor,missing)]) await expect(command()).rejects.toMatchObject({code:'P0002'}) }))
 it('keeps every visible relationship toggle idempotent through bounded commands',async()=>tx(async c=>{ const actor=await human(c),author=await ip(c),postId=await post(c,author),social=repo(c); await expect(social.follow(actor,author,context())).resolves.toEqual({created:true}); await expect(social.follow(actor,author,context())).resolves.toEqual({created:false}); await expect(social.unfollow(actor,author)).resolves.toEqual({deleted:true}); await expect(social.unfollow(actor,author)).resolves.toEqual({deleted:false}); await expect(social.likePost(actor,postId,context())).resolves.toEqual({created:true}); await expect(social.likePost(actor,postId,context())).resolves.toEqual({created:false}); await expect(social.unlikePost(actor,postId)).resolves.toEqual({deleted:true}); await expect(social.unlikePost(actor,postId)).resolves.toEqual({deleted:false}); await expect(social.bookmarkPost(actor,postId)).resolves.toEqual({created:true}); await expect(social.bookmarkPost(actor,postId)).resolves.toEqual({created:false}); await expect(social.unbookmarkPost(actor,postId)).resolves.toEqual({deleted:true}); await expect(social.unbookmarkPost(actor,postId)).resolves.toEqual({deleted:false}) }))
 it('exposes only bounded authenticated command signatures and no direct relationship writes',async()=>tx(async c=>{ await c.query('SET LOCAL ROLE aifans_authenticated'); const privileges=await c.query<{old_follow:boolean;old_like:boolean;old_comment:boolean;new_follow:boolean;new_like:boolean;new_comment:boolean;follows_insert:boolean;follows_delete:boolean;likes_insert:boolean;likes_delete:boolean;bookmarks_insert:boolean;bookmarks_delete:boolean;likes_select:boolean;bookmarks_select:boolean}>(`SELECT has_function_privilege(current_user,'public.follow_profile(uuid,uuid,uuid,text)','EXECUTE') old_follow,has_function_privilege(current_user,'public.like_post(uuid,uuid,uuid,text)','EXECUTE') old_like,has_function_privilege(current_user,'public.create_human_comment(uuid,uuid,uuid,text,uuid,uuid,text)','EXECUTE') old_comment,has_function_privilege(current_user,'public.follow_profile(uuid,uuid)','EXECUTE') new_follow,has_function_privilege(current_user,'public.like_post(uuid,uuid)','EXECUTE') new_like,has_function_privilege(current_user,'public.create_human_comment(uuid,uuid,text,uuid)','EXECUTE') new_comment,has_table_privilege(current_user,'public.follows','INSERT') follows_insert,has_table_privilege(current_user,'public.follows','DELETE') follows_delete,has_table_privilege(current_user,'public.post_likes','INSERT') likes_insert,has_table_privilege(current_user,'public.post_likes','DELETE') likes_delete,has_table_privilege(current_user,'public.bookmarks','INSERT') bookmarks_insert,has_table_privilege(current_user,'public.bookmarks','DELETE') bookmarks_delete,has_table_privilege(current_user,'public.post_likes','SELECT') likes_select,has_table_privilege(current_user,'public.bookmarks','SELECT') bookmarks_select`); expect(privileges.rows[0]).toEqual({old_follow:false,old_like:false,old_comment:false,new_follow:true,new_like:true,new_comment:true,follows_insert:false,follows_delete:false,likes_insert:false,likes_delete:false,bookmarks_insert:false,bookmarks_delete:false,likes_select:true,bookmarks_select:true}) }))
 it('grants only authenticated callers the bounded followed-IP projection',async()=>tx(async c=>{ const privileges=await c.query<{authenticated:boolean;anonymous:boolean;platform:boolean;direct_select:boolean}>(`SELECT has_function_privilege('aifans_authenticated','public.social_followed_ip_profiles(timestamptz,uuid,integer)','EXECUTE') authenticated,has_function_privilege('aifans_anon','public.social_followed_ip_profiles(timestamptz,uuid,integer)','EXECUTE') anonymous,has_function_privilege('aifans_platform','public.social_followed_ip_profiles(timestamptz,uuid,integer)','EXECUTE') platform,has_table_privilege('aifans_authenticated','public.follows','SELECT') direct_select`); expect(privileges.rows[0]).toEqual({authenticated:true,anonymous:false,platform:false,direct_select:false}) }))
 it('projects comments only for public posts and nulls deleted bodies at the SQL boundary',async()=>tx(async c=>{ const humanAuthor=await human(c), ipAuthor=await ip(c), postId=await post(c,ipAuthor); const hiddenIp=await ip(c,'draft'),hiddenPost=await post(c,hiddenIp),draftPost=await post(c,ipAuthor,'draft'); const ids=[randomUUID(),randomUUID(),randomUUID()]; await c.query(`INSERT INTO public.comments(id,post_id,author_profile_id,source,body) VALUES($1,$2,$3,'human','one'),($4,$2,$5,'worker','two'),($6,$2,$3,'human','three')`,[ids[0],postId,humanAuthor.id,ids[1],ipAuthor,ids[2]]); await c.query(`UPDATE public.comments SET state='deleted',deleted_at=clock_timestamp() WHERE id=$1`,[ids[2]]); const raw=await c.query('SELECT id,author_id,author_kind,body FROM public.social_public_comments($1,NULL,NULL,10)',[postId]); expect(raw.rows.find(r=>r.id===ids[1])?.author_kind).toBe('ip'); expect(raw.rows.find(r=>r.id===ids[2])?.body).toBeNull(); await expect(c.query('SELECT * FROM public.social_public_comments($1,NULL,NULL,10)',[hiddenPost])).resolves.toMatchObject({rowCount:0}); await expect(c.query('SELECT * FROM public.social_public_comments($1,NULL,NULL,10)',[draftPost])).resolves.toMatchObject({rowCount:0}); const social=repo(c); const first=await social.getPost({viewer:null,postId,commentLimit:2,commentAfter:null}); const cursor=first?.comments.nextCursor; expect(cursor).toBeTruthy(); const decoded=JSON.parse(Buffer.from(cursor!,'base64url').toString('utf8')); const second=await social.getPost({viewer:null,postId,commentLimit:2,commentAfter:decoded}); const all=[...(first?.comments.items??[]),...(second?.comments.items??[])]; expect(all.map(x=>x.id).sort()).toEqual(ids.slice().sort()); expect(all.map(x=>x.author.kind)).toContain('ip'); expect(all.find(x=>x.id===ids[2])).toMatchObject({state:'deleted'}); expect(all.find(x=>x.id===ids[2])).not.toHaveProperty('body') }))

 it('returns newly created human comments with a human author',async()=>tx(async c=>{ const actor=await human(c),author=await ip(c),postId=await post(c,author),social=repo(c); const created=await social.createHumanComment(actor,postId,{body:'human words'},context()); expect(created).toMatchObject({postId,body:'human words',author:{kind:'human',id:actor.id}}) }))
 it('notifies the published top-level parent author and rejects every invalid reply parent',async()=>tx(async c=>{ const postAuthor=await ip(c),parentAuthor=await human(c),replier=await human(c),otherPostAuthor=await ip(c),postId=await post(c,postAuthor),otherPost=await post(c,otherPostAuthor),social=repo(c); const parent=await social.createHumanComment(parentAuthor,postId,{body:'parent'},context()); const reply=await social.createHumanComment(replier,postId,{body:'reply',parentCommentId:parent.id},context()); await expect(c.query("SELECT recipient_profile_id,kind FROM public.notifications WHERE comment_id=$1",[reply.id])).resolves.toMatchObject({rows:[{recipient_profile_id:parentAuthor.id,kind:'reply'}]}); const nested=await social.createHumanComment(parentAuthor,postId,{body:'self reply',parentCommentId:parent.id},context()); await expect(c.query('SELECT 1 FROM public.notifications WHERE comment_id=$1',[nested.id])).resolves.toMatchObject({rowCount:0}); await c.query("UPDATE public.comments SET state='deleted',deleted_at=clock_timestamp() WHERE id=$1",[parent.id]); await expect(social.createHumanComment(replier,postId,{body:'deleted',parentCommentId:parent.id},context())).rejects.toThrow('invalid reply parent'); const wrong=await social.createHumanComment(parentAuthor,otherPost,{body:'wrong post parent'},context()); await expect(social.createHumanComment(replier,postId,{body:'wrong',parentCommentId:wrong.id},context())).rejects.toThrow('invalid reply parent'); await expect(social.createHumanComment(replier,postId,{body:'nested',parentCommentId:reply.id},context())).rejects.toThrow('invalid reply parent'); await expect(social.createHumanComment(replier,postId,{body:'missing',parentCommentId:randomUUID()},context())).rejects.toThrow('invalid reply parent') }))
 it('rejects a comment when a concurrent post withdrawal wins the visibility lock',async()=>expectVisibilityChangeToWin(async(client,{postId})=>{await client.query("UPDATE public.posts SET state='withdrawn',withdrawn_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=$1",[postId])}))
 it('rejects a comment when a concurrent IP unpublish wins the visibility lock',async()=>expectVisibilityChangeToWin(async(client,{author})=>{await client.query("UPDATE public.ip_profiles SET public_state='unpublished',operation_enabled=false,updated_at=clock_timestamp() WHERE profile_id=$1",[author])}))
 it('keeps bookmarks private and bookmark toggles idempotent',async()=>tx(async c=>{ const author=await ip(c); const postId=await post(c,author); const first=await human(c),second=await human(c); const social=repo(c); await expect(social.bookmarkPost(first,postId)).resolves.toEqual({created:true}); await expect(social.bookmarkPost(first,postId)).resolves.toEqual({created:false}); await expect(social.listBookmarks(first,{limit:10})).resolves.toMatchObject({items:[{id:postId}]}); await expect(social.listBookmarks(second,{limit:10})).resolves.toEqual({items:[],nextCursor:null}); await expect(social.unbookmarkPost(first,postId)).resolves.toEqual({deleted:true}); await expect(social.unbookmarkPost(first,postId)).resolves.toEqual({deleted:false}) }))
 it('lists only an owner’s followed published IPs across stable cursor pages',async()=>tx(async c=>{ const older=await ip(c),newer=await ip(c),hidden=await ip(c,'draft'),otherIp=await ip(c),actor=await human(c),other=await human(c); await c.query(`UPDATE public.ip_profiles SET created_at=CASE profile_id WHEN $1 THEN '2026-09-01T00:00:00.000100Z'::timestamptz WHEN $2 THEN '2026-09-01T00:00:00.000900Z'::timestamptz ELSE created_at END WHERE profile_id IN ($1,$2)`,[older,newer]); await c.query(`INSERT INTO public.follows(follower_profile_id,followed_profile_id) VALUES($1,$2),($1,$3),($1,$4),($5,$6)`,[actor.id,older,newer,hidden,other.id,otherIp]); const social=repo(c); const first=await social.listFollowedIps(actor,{limit:1}); expect(first.items).toEqual([expect.objectContaining({id:newer,followerCount:1})]); expect(decodeFollowedIpCursor(first.nextCursor!)).toMatchObject({kind:'followed_ips',id:newer}); const second=await social.listFollowedIps(actor,{limit:10,cursor:first.nextCursor!}); expect(second).toEqual({items:[expect.objectContaining({id:older,followerCount:1})],nextCursor:null}); await expect(social.listFollowedIps(other,{limit:10})).resolves.toEqual({items:[expect.objectContaining({id:otherIp,followerCount:1})],nextCursor:null}) }))
 it('filters hidden followed IPs before applying the projection page bound',async()=>tx(async c=>{ const actor=await human(c),visible=await ip(c),hiddenIds=await Promise.all(Array.from({length:51},()=>ip(c,'draft'))); await c.query(`UPDATE public.ip_profiles SET created_at='2026-09-01T00:00:00.000100Z' WHERE profile_id=$1`,[visible]); await c.query(`INSERT INTO public.follows(follower_profile_id,followed_profile_id) SELECT $1,id FROM unnest($2::uuid[]) ids(id)`,[actor.id,[visible,...hiddenIds]]); const rows=await createActorSession({connect:async()=>({query:c.query.bind(c),release(){}})},{transactionMode:'nested'}).withActor(actor,async client=>(await client.query<{id:string}>('SELECT id FROM public.social_followed_ip_profiles(NULL,NULL,51)')).rows); expect(rows).toEqual([{id:visible}]) }))
 it('rejects wrong-kind cursors for bookmark pages',async()=>tx(async c=>{ const actor=await human(c); const social=repo(c); const wrong=encodeCursor({v:1,kind:'for_you',score:0,publishedAt:'2026-09-01T00:00:00.000Z',id:randomUUID()}); await expect(social.listBookmarks(actor,{limit:10,cursor:wrong})).rejects.toThrow('INVALID_CURSOR') }))
 it('lists only an owner’s liked published posts with a stable liked cursor',async()=>tx(async c=>{ const author=await ip(c),otherAuthor=await ip(c),actor=await human(c),other=await human(c),visibleOld=await post(c,author,'published','2026-09-01T00:00:00.000000Z'),visibleNew=await post(c,author,'published','2026-09-01T01:00:00.000000Z'),draft=await post(c,author,'draft'),withdrawn=await post(c,author,'withdrawn','2026-09-01T02:00:00.000000Z'),otherPost=await post(c,otherAuthor),social=repo(c); await c.query(`INSERT INTO public.post_likes(post_id,profile_id,created_at) VALUES($1,$2,'2026-09-02T00:00:00.000100Z'),($3,$2,'2026-09-02T00:00:00.000900Z'),($4,$2,'2026-09-02T00:00:00.001100Z'),($5,$2,'2026-09-02T00:00:00.001500Z'),($6,$7,'2026-09-02T00:00:00.002000Z')`,[visibleOld,actor.id,visibleNew,draft,withdrawn,otherPost,other.id]); const first=await social.listLiked(actor,{limit:1}); expect(first.items.map(x=>x.id)).toEqual([visibleNew]); expect(first.nextCursor).toBeTruthy(); const cursor=decodeLikedCursor(first.nextCursor!); expect(cursor).toMatchObject({kind:'liked',likedAt:'2026-09-02T00:00:00.000900Z'}); const second=await social.listLiked(actor,{limit:10,cursor:first.nextCursor!}); expect(second.items.map(x=>x.id)).toEqual([visibleOld]); await expect(social.listLiked(other,{limit:10})).resolves.toEqual({items:[expect.objectContaining({id:otherPost})],nextCursor:null}) }))
 it('rejects non-liked cursors for liked pages',async()=>tx(async c=>{ const actor=await human(c),social=repo(c); const wrong=encodeCursor({v:1,kind:'for_you',score:0,publishedAt:'2026-09-01T00:00:00.000Z',id:randomUUID()}); await expect(social.listLiked(actor,{limit:10,cursor:wrong})).rejects.toThrow('INVALID_CURSOR') }))
 it('paginates all owned notifications without duplicates at database microsecond precision',async()=>tx(async c=>{ const recipient=await human(c),other=await human(c),humanActor=await human(c),ipActor=await ip(c); const ids=[randomUUID(),randomUUID(),randomUUID()]; await c.query(`INSERT INTO public.notifications(id,recipient_profile_id,actor_profile_id,kind,created_at) VALUES($1,$2,$3,'follow','2026-09-01T00:00:00.000100Z'),($4,$2,$3,'follow','2026-09-01T00:00:00.000900Z'),($5,$2,$6,'follow','2026-09-01T00:00:00.001100Z')`,[ids[0],recipient.id,humanActor.id,ids[1],ids[2],ipActor]); const social=repo(c); const found:string[]=[]; let cursor:string|undefined; do { const page=await social.listNotifications(recipient,{limit:1,...(cursor?{cursor}:{})}); found.push(...page.items.map(item=>item.id)); if (page.items[0]?.id===ids[2]) expect(page.items[0].actor).toMatchObject({kind:'ip',id:ipActor}); if (page.items[0]?.id===ids[1]) expect(page.items[0].actor).toMatchObject({kind:'human',id:humanActor.id}); cursor=page.nextCursor??undefined } while(cursor); expect(found).toEqual([ids[2],ids[1],ids[0]]); expect(new Set(found).size).toBe(ids.length); await expect(social.listNotifications(other,{limit:10})).resolves.toEqual({items:[],nextCursor:null}); await expect(social.listNotifications(recipient,{limit:1,cursor:notificationCursor('2026-09-01T00:00:00.000Z',randomUUID())})).resolves.toEqual({items:[],nextCursor:null}) }))
 it('normalizes malformed notification cursors to INVALID_CURSOR',async()=>tx(async c=>{ const recipient=await human(c),social=repo(c); const invalid=Buffer.from(JSON.stringify({v:1,kind:'notifications',createdAt:'2026-09-01T00:00:00.000Z',id:randomUUID(),extra:true}),'utf8').toString('base64url'); await expect(social.listNotifications(recipient,{limit:1,cursor:invalid})).rejects.toThrow('INVALID_CURSOR') }))
 it('marks an owned notification read safely under concurrent idempotent calls',async()=>tx(async c=>{ const recipient=await human(c),other=await human(c),actor=await human(c),id=randomUUID(); await c.query(`INSERT INTO public.notifications(id,recipient_profile_id,actor_profile_id,kind) VALUES($1,$2,$3,'follow')`,[id,recipient.id,actor.id]); const social=repo(c); const [first,second]=await Promise.all([social.markNotificationRead(recipient,id),social.markNotificationRead(recipient,id)]); expect(first?.readAt).toBeTruthy(); expect(second).toEqual(first); await expect(social.markNotificationRead(other,id)).resolves.toBeNull() }))
 it('writes correlated event and outbox atomically through the bounded command',async()=>tx(async c=>{ const actor=await human(c),author=await ip(c),postId=await post(c,author),social=repo(c),command=context(); await expect(social.likePost(actor,postId,command)).resolves.toEqual({created:true}); const result=await c.query(`SELECT e.id,e.request_id,e.environment,o.business_event_id,o.payload FROM public.business_events e JOIN public.analytics_outbox o ON o.business_event_id=e.id WHERE e.event_name='post_liked' AND e.actor_profile_id=$1 AND e.subject_entity_id=$2`,[actor.id,postId]); expect(result.rows).toHaveLength(1); expect(result.rows[0]).toMatchObject({request_id:command.requestId,environment:'api',business_event_id:result.rows[0]?.id,payload:{event_id:result.rows[0]?.id,event_name:'post_liked',event_version:1,request_id:command.requestId}}) }))
 it('rolls back the like, history event, and notification when outbox insertion fails',async()=>tx(async c=>{ const actor=await human(c),author=await ip(c),postId=await post(c,author); const social=repo(c); await c.query(`CREATE FUNCTION pg_temp.reject_social_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced outbox failure'; END $$`); await c.query(`CREATE TRIGGER reject_social_outbox BEFORE INSERT ON public.analytics_outbox FOR EACH ROW EXECUTE FUNCTION pg_temp.reject_social_outbox()`); await expect(social.likePost(actor,postId,context())).rejects.toThrow('forced outbox failure'); await expect(c.query('SELECT 1 FROM public.post_likes WHERE post_id=$1 AND profile_id=$2',[postId,actor.id])).resolves.toMatchObject({rowCount:0}); await expect(c.query("SELECT 1 FROM public.business_events WHERE actor_profile_id=$1 AND subject_entity_id=$2 AND event_name='post_liked'",[actor.id,postId])).resolves.toMatchObject({rowCount:0}); await expect(c.query("SELECT 1 FROM public.notifications WHERE recipient_profile_id=$1 AND actor_profile_id=$2 AND post_id=$3 AND kind='post_like'",[author,actor.id,postId])).resolves.toMatchObject({rowCount:0}) }))
})
