import {randomUUID} from 'node:crypto'
import {Pool, type PoolClient} from 'pg'
import {afterAll, describe, expect, it} from 'vitest'
import {decodeCursor, encodeCursor} from '@aifans/contracts'
import {createSocialRepository} from '../src/social.js'
import {createActorSession} from '../src/session.js'

const connectionString=process.env.DATABASE_URL ?? ''
const integration=connectionString ? describe : describe.skip
const pool=new Pool({connectionString})
async function tx<T>(fn:(c:PoolClient)=>Promise<T>) { const c=await pool.connect(); try { await c.query('BEGIN'); return await fn(c) } finally { await c.query('ROLLBACK').catch(()=>undefined); c.release() } }
async function human(c:PoolClient) { const id=randomUUID(), subject=`fixture-${randomUUID()}`; await c.query(`INSERT INTO public.profiles(id,auth_subject,account_kind,username,display_name) VALUES($1,$2,'human',$3,'Human')`,[id,subject,`h_${id.replaceAll('-','').slice(0,20)}`]); return {id,subject} }
async function ip(c:PoolClient, state:'published'|'draft'='published') { const id=randomUUID(), revision=randomUUID(); await c.query(`INSERT INTO public.profiles(id,account_kind,username,display_name) VALUES($1,'ip',$2,'IP')`,[id,`i_${id.replaceAll('-','').slice(0,20)}`]); await c.query(`INSERT INTO public.ip_profiles(profile_id,source,public_state,operation_enabled,current_identity_revision_id) VALUES($1,'platform',$2,true,$3)`,[id,state,revision]); await c.query(`INSERT INTO public.ip_identity_revisions(id,ip_profile_id,version,display_name,languages) VALUES($1,$2,1,'IP',ARRAY['en'])`,[revision,id]); return id }
async function post(c:PoolClient, author:string, state:'published'|'draft'|'withdrawn'='published', publishedAt?:string) { const id=randomUUID(); await c.query(`INSERT INTO public.posts(id,author_profile_id,source,state,body${state==='published'?' ,published_at':''}${state==='withdrawn'?' ,published_at,withdrawn_at':''}) VALUES($1,$2,'worker',$3,'fixture'${state==='published'?',$4::timestamptz':''}${state==='withdrawn'?',$4::timestamptz,$4::timestamptz':''})`,state==='draft'?[id,author,state]:[id,author,state,publishedAt??new Date().toISOString()]); return id }
function notificationCursor(createdAt:string,id:string) { return Buffer.from(JSON.stringify({v:1,kind:'notifications',createdAt,id}),'utf8').toString('base64url') }
function repo(c:PoolClient) { const session=createActorSession({connect:async()=>({query:c.query.bind(c),release(){}})}); return createSocialRepository({withActor:session.withActor,withPublic:async(fn)=>{await c.query('SAVEPOINT anon'); try {await c.query('SET LOCAL ROLE aifans_anon'); await c.query("SELECT set_config('request.jwt.claims','{}',true)"); const value=await fn({query:c.query.bind(c),release(){}}); await c.query('ROLLBACK TO SAVEPOINT anon'); return value} finally {await c.query('RELEASE SAVEPOINT anon').catch(()=>undefined)}}}) }

integration('social repository local postgres',()=>{
 afterAll(async()=>pool.end())
 it('returns only published public posts and keeps viewer flags actor-scoped',async()=>tx(async c=>{
  const author=await ip(c); const hidden=await ip(c,'draft'); const visible=await post(c,author); await post(c,hidden); await post(c,author,'withdrawn');
  const first=await human(c), second=await human(c); const social=repo(c);
  const ownerProjection=await c.query('SELECT post_id FROM public.social_public_posts()'); expect(ownerProjection.rows.map((row)=>row.post_id)).toContain(visible);
  await c.query('SAVEPOINT diagnostic_anon'); await c.query('SET LOCAL ROLE aifans_anon'); const anonProjection=await c.query('SELECT post_id FROM public.social_public_posts()'); const flags=await c.query('SELECT * FROM public.social_viewer_flags($1,$2)',[visible,author]); const metrics=await c.query('SELECT * FROM public.social_post_metrics($1,$2,$3)',[visible,author,'en']); const identity=await c.query("SELECT current_user, current_setting('request.jwt.claims',true) AS claims"); await c.query('ROLLBACK TO SAVEPOINT diagnostic_anon'); await c.query('RELEASE SAVEPOINT diagnostic_anon'); expect(identity.rows[0]?.current_user).toBe('aifans_anon'); expect(anonProjection.rows.map((row)=>row.post_id)).toContain(visible); expect(flags.rows).toHaveLength(1); expect(metrics.rows).toHaveLength(1);
  await social.likePost(first,visible); await social.bookmarkPost(first,visible); await social.follow(first,author);
  const anon=await social.listFeed({viewer:null,kind:'for_you',limit:25,after:null}); expect(anon.items.map(x=>x.id)).toEqual([visible]); expect(anon.items[0]?.likeCount).toBe(1); expect(anon.items[0]?.viewerHasLiked).toBe(false);
  const mine=await social.listFeed({viewer:first,kind:'for_you',limit:25,after:null}); expect(mine.items[0]).toMatchObject({viewerHasLiked:true,viewerHasBookmarked:true,viewerFollowsAuthor:true});
  const other=await social.listFeed({viewer:second,kind:'for_you',limit:25,after:null}); expect(other.items[0]).toMatchObject({viewerHasLiked:false,viewerHasBookmarked:false,viewerFollowsAuthor:false});
 }))
 it('paginates every feed post once while preserving database microseconds',async()=>tx(async c=>{ const author=await ip(c); const ids=[await post(c,author,'published','2026-09-01T00:00:00.000100Z'),await post(c,author,'published','2026-09-01T00:00:00.000500Z'),await post(c,author,'published','2026-09-01T00:00:00.000900Z')]; const viewer=await human(c),social=repo(c); await social.follow(viewer,author); for (const kind of ['for_you','following'] as const) { const found:string[]=[]; let after=null; do { const page=await social.listFeed({viewer:kind==='following'?viewer:null,kind,limit:1,after}); found.push(...page.items.map(item=>item.id)); after=page.nextCursor?decodeCursor(page.nextCursor,kind):null } while(after); expect(found).toEqual(ids.slice().reverse()); expect(new Set(found).size).toBe(ids.length) } }))
 it('rejects comments on hidden posts and follows of non-public IPs',async()=>tx(async c=>{ const actor=await human(c); const author=await ip(c); const draft=await post(c,author,'draft'); const withdrawn=await post(c,author,'withdrawn'); const hidden=await ip(c,'draft'); const social=repo(c); await expect(social.createHumanComment(actor,draft,{body:'no'})).rejects.toThrow(); await expect(social.createHumanComment(actor,withdrawn,{body:'no'})).rejects.toThrow(); await expect(social.follow(actor,hidden)).rejects.toThrow() }))
 it('projects comment authors and paginates comments without bodies for deleted nodes',async()=>tx(async c=>{ const humanAuthor=await human(c), ipAuthor=await ip(c), postId=await post(c,ipAuthor); const ids=[randomUUID(),randomUUID(),randomUUID()]; await c.query(`INSERT INTO public.comments(id,post_id,author_profile_id,source,body) VALUES($1,$2,$3,'human','one'),($4,$2,$5,'worker','two'),($6,$2,$3,'human','three')`,[ids[0],postId,humanAuthor.id,ids[1],ipAuthor,ids[2]]); await c.query(`UPDATE public.comments SET state='deleted',deleted_at=clock_timestamp() WHERE id=$1`,[ids[2]]); const raw=await c.query('SELECT id,author_id,author_kind FROM public.social_public_comments($1,NULL,NULL,10)',[postId]); expect(raw.rows.find(r=>r.id===ids[1])?.author_kind).toBe('ip'); const social=repo(c); const first=await social.getPost({viewer:null,postId,commentLimit:2,commentAfter:null}); const cursor=first?.comments.nextCursor; expect(cursor).toBeTruthy(); const decoded=JSON.parse(Buffer.from(cursor!,'base64url').toString('utf8')); const second=await social.getPost({viewer:null,postId,commentLimit:2,commentAfter:decoded}); const all=[...(first?.comments.items??[]),...(second?.comments.items??[])]; expect(all.map(x=>x.id).sort()).toEqual(ids.slice().sort()); expect(all.map(x=>x.author.kind)).toContain('ip'); expect(all.find(x=>x.id===ids[2])).toMatchObject({state:'deleted'}); expect(all.find(x=>x.id===ids[2])).not.toHaveProperty('body') }))
 it('keeps bookmarks private and bookmark toggles idempotent',async()=>tx(async c=>{ const author=await ip(c); const postId=await post(c,author); const first=await human(c),second=await human(c); const social=repo(c); await expect(social.bookmarkPost(first,postId)).resolves.toEqual({created:true}); await expect(social.bookmarkPost(first,postId)).resolves.toEqual({created:false}); await expect(social.listBookmarks(first,{limit:10})).resolves.toMatchObject({items:[{id:postId}]}); await expect(social.listBookmarks(second,{limit:10})).resolves.toEqual({items:[],nextCursor:null}); await expect(social.unbookmarkPost(first,postId)).resolves.toEqual({deleted:true}); await expect(social.unbookmarkPost(first,postId)).resolves.toEqual({deleted:false}) }))
 it('rejects wrong-kind cursors for bookmark pages',async()=>tx(async c=>{ const actor=await human(c); const social=repo(c); const wrong=encodeCursor({v:1,kind:'for_you',score:0,publishedAt:'2026-09-01T00:00:00.000Z',id:randomUUID()}); await expect(social.listBookmarks(actor,{limit:10,cursor:wrong})).rejects.toThrow('INVALID_CURSOR') }))
 it('paginates all owned notifications without duplicates at database microsecond precision',async()=>tx(async c=>{ const recipient=await human(c),other=await human(c),humanActor=await human(c),ipActor=await ip(c); const ids=[randomUUID(),randomUUID(),randomUUID()]; await c.query(`INSERT INTO public.notifications(id,recipient_profile_id,actor_profile_id,kind,created_at) VALUES($1,$2,$3,'follow','2026-09-01T00:00:00.000100Z'),($4,$2,$3,'follow','2026-09-01T00:00:00.000900Z'),($5,$2,$6,'follow','2026-09-01T00:00:00.001100Z')`,[ids[0],recipient.id,humanActor.id,ids[1],ids[2],ipActor]); const social=repo(c); const found:string[]=[]; let cursor:string|undefined; do { const page=await social.listNotifications(recipient,{limit:1,...(cursor?{cursor}:{})}); found.push(...page.items.map(item=>item.id)); if (page.items[0]?.id===ids[2]) expect(page.items[0].actor).toMatchObject({kind:'ip',id:ipActor}); if (page.items[0]?.id===ids[1]) expect(page.items[0].actor).toMatchObject({kind:'human',id:humanActor.id}); cursor=page.nextCursor??undefined } while(cursor); expect(found).toEqual([ids[2],ids[1],ids[0]]); expect(new Set(found).size).toBe(ids.length); await expect(social.listNotifications(other,{limit:10})).resolves.toEqual({items:[],nextCursor:null}); await expect(social.listNotifications(recipient,{limit:1,cursor:notificationCursor('2026-09-01T00:00:00.000Z',randomUUID())})).resolves.toEqual({items:[],nextCursor:null}) }))
 it('marks an owned notification read idempotently and hides it from other users',async()=>tx(async c=>{ const recipient=await human(c),other=await human(c),actor=await human(c),id=randomUUID(); await c.query(`INSERT INTO public.notifications(id,recipient_profile_id,actor_profile_id,kind) VALUES($1,$2,$3,'follow')`,[id,recipient.id,actor.id]); const social=repo(c); const first=await social.markNotificationRead(recipient,id); expect(first?.readAt).toBeTruthy(); await expect(social.markNotificationRead(recipient,id)).resolves.toEqual(first); await expect(social.markNotificationRead(other,id)).resolves.toBeNull() }))
 it('rolls back the like, history event, and notification when outbox insertion fails',async()=>tx(async c=>{ const actor=await human(c),author=await ip(c),postId=await post(c,author); const social=repo(c); await c.query(`CREATE FUNCTION pg_temp.reject_social_outbox() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced outbox failure'; END $$`); await c.query(`CREATE TRIGGER reject_social_outbox BEFORE INSERT ON public.analytics_outbox FOR EACH ROW EXECUTE FUNCTION pg_temp.reject_social_outbox()`); await expect(social.likePost(actor,postId)).rejects.toThrow('forced outbox failure'); await expect(c.query('SELECT 1 FROM public.post_likes WHERE post_id=$1 AND profile_id=$2',[postId,actor.id])).resolves.toMatchObject({rowCount:0}); await expect(c.query("SELECT 1 FROM public.business_events WHERE actor_profile_id=$1 AND subject_entity_id=$2 AND event_name='post_liked'",[actor.id,postId])).resolves.toMatchObject({rowCount:0}); await expect(c.query("SELECT 1 FROM public.notifications WHERE recipient_profile_id=$1 AND actor_profile_id=$2 AND post_id=$3 AND kind='post_like'",[author,actor.id,postId])).resolves.toMatchObject({rowCount:0}) }))
})
